### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#117]
```ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OmniSharp.Extensions.StringExtensions.FirstLetterMatches(String word, String match) in C:\Users\jrieken\Code\omnisharp-roslyn\src\Omnisharp\Extensions\StringExtensions.cs:line 45
   at OmniSharp.Extensions.StringExtensions.IsSubsequenceMatch(String completion, String partial) in C:\Users\jrieken\Code\omnisharp-roslyn\src\Omnisharp\Extensions\StringExtensions.cs:line 35
   at OmniSharp.Extensions.StringExtensions.IsValidCompletionFor(String completion, String partial) in C:\Users\jrieken\Code\omnisharp-roslyn\src\Omnisharp\Extensions\StringExtensions.cs:line 9
   at OmniSharp.OmnisharpController.<>c__DisplayClass13_0.<AutoComplete>b__0(ISymbol s) in C:\Users\jrieken\Code\omnisharp-roslyn\src\Omnisharp\Api\Intellisense\OmnisharpController.Intellisense.cs:line 36
   at System.Linq.Enumerable.<>c__DisplayClass2`1.<CombinePredicates>b__4(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OmniSharp.OmnisharpController.<AutoComplete>d__13.MoveNext() in C:\Users\jrieken\Code\omnisharp-roslyn\src\Omnisharp\Api\Intellisense\OmnisharpController.Intellisense.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()```

**Comment by nosami** [comment]
I've seen this too... but can't replicate now. Can you remember how to trigger this? 

It looks like a simple fix, but I want to write a test for it.

**Comment by jrieken** [comment]
I'll keep my eyes open - my impression was that this happens on namespaces but I cannot reproduce either...

**Comment by jrieken** [comment]
should be fixed with https://github.com/OmniSharp/omnisharp-roslyn/pull/118
