### ISSUE TITLE
Omnisharp server fails to start 

### ISSUE THREAD

**Issue by TyOverby** [OmniSharp/omnisharp-roslyn#1219]
```
Starting OmniSharp server at 6/7/2018, 12:57:34 PM
    Target: f:\workspace\c#\MLS-LS\MLS-LS.sln

OmniSharp server started
    Path: C:\Users\Ty\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe
    PID: 13956

System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at OmniSharp.MSBuild.Discovery.Interop.GetSetupConfiguration()
   at OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider.GetInstances()
   at OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances()
   at OmniSharp.CompositionHostBuilder.RegisterMSBuildInstance(IMSBuildLocator msbuildLocator, ILogger logger)
   at OmniSharp.CompositionHostBuilder.Build()
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IConfiguration configuration, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource)
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OmniSharp.HostHelpers.Start(Func`1 action)
```

**Comment by TyOverby** [comment]
I've completely uninstalled visual studio from this machine.

**Comment by DustinCampbell** [comment]
Hey @TyOverby -- Did you remove the VS Installer as well? It sounds to me like the Visual Studio Installer didn't get unintalled properly and left some bits in the Windows registry.

If you look in regedit.exe, do you see any of these keys? You can just search for `{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}`.

* `HKEY_CLASSES_ROOT\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}`
* `HKEY_CLASSES_ROOT\Microsoft.VisualStudio.Setup.Configuration`
* `HKEY_CLASSES_ROOT\Microsoft.VisualStudio.Setup.Configuration.1`
* `HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}`
* `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}`
* `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Microsoft.VisualStudio.Setup.Configuration`
* `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Microsoft.VisualStudio.Setup.Configuration.1`
* `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}`
* `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}`

If you've completely removed Visual Studio and the Visual Studio Installer, maybe try deleting those keys. These register the COM factory for the Visual Studio setup API. The exception you posted above would indicate that the native binary that the COM factory lives in has been removed from your machine.

**Comment by TyOverby** [comment]
I uninstalled with https://github.com/Microsoft/VisualStudioUninstaller which typically does a pretty good job.

I have since re-installed Visual Studio, so most of those keys are present...  I'll close this for now, and if I encounter the bug again I'll re-open and keep from installing visual studio haha

**Comment by DustinCampbell** [comment]
dogfood @TyOverby . It's important. :smile:
