### ISSUE TITLE
OmniSharp server crashes on startup

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-roslyn#1224]
_From @ignusin on June 12, 2018 16:54_

Hello OmniSharp/VSCode team.
IntelliSense doesn't work in my AspNetCore 2.0 project.
OmniSharp fails with following exception copied from OmniSharp Log in VSCode.
Could you please take a look?

- Extension Name: csharp
- Extension Version: 1.15.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.24.0

System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Microsoft.VisualStudio.Setup.Configuration.ISetupInstance2.GetState()
   at OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider.GetInstances()
   at OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances()
   at OmniSharp.CompositionHostBuilder.RegisterMSBuildInstance(IMSBuildLocator msbuildLocator, ILogger logger)
   at OmniSharp.CompositionHostBuilder.Build()
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IConfiguration configuration, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource)
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OmniSharp.HostHelpers.Start(Func`1 action)

_Copied from original issue: OmniSharp/omnisharp-vscode#2379_

**Comment by ignusin** [comment]
Sorry guys, this is 100% my local issue.
I upgraded Visual Studio 2017 to 15.7.3 and everything started to work like a charm!

**Comment by DustinCampbell** [comment]
Thanks for letting us know. Glad to hear it's solved!
