### ISSUE TITLE
Unit test failing in master branch

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-roslyn#1255]
Test Name:	OmniSharp.Script.Tests.WorkspaceInformationTests.CsiScriptWithFileCreatedAfterStartingServer
Test FullName:	OmniSharp.Script.Tests.WorkspaceInformationTests.CsiScriptWithFileCreatedAfterStartingServer
Test Source:	C:\Users\akagarw\Work\omnisharp-roslyn\tests\OmniSharp.Script.Tests\WorkspaceInformationTests.cs : line 50
Test Outcome:	Failed
Test Duration:	0:00:00.002

Result StackTrace:	
at OmniSharp.Services.OmniSharpEnvironment..ctor(String path, Int32 hostPid, LogLevel logLevel, String[] additionalArguments) in C:\Users\akagarw\Work\omnisharp-roslyn\src\OmniSharp.Host\Services\OmniSharpEnvironment.cs:line 41
   at TestUtility.OmniSharpTestHost.Create(String path, ITestOutputHelper testOutput, IEnumerable`1 configurationData, DotNetCliVersion dotNetCliVersion, IEnumerable`1 additionalExports) in C:\Users\akagarw\Work\omnisharp-roslyn\tests\TestUtility\OmniSharpTestHost.cs:line 100
   at TestUtility.AbstractTestFixture.CreateOmniSharpHost(String path, IEnumerable`1 configurationData, DotNetCliVersion dotNetCliVersion, IEnumerable`1 additionalExports) in C:\Users\akagarw\Work\omnisharp-roslyn\tests\TestUtility\AbstractTestFixture.cs:line 57
   at OmniSharp.Script.Tests.WorkspaceInformationTests.<CsiScriptWithFileCreatedAfterStartingServer>d__3.MoveNext() in C:\Users\akagarw\Work\omnisharp-roslyn\tests\OmniSharp.Script.Tests\WorkspaceInformationTests.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
System.ArgumentException : OmniSharp only supports being launched with a directory path or a path to a solution (.sln) file.
Parameter name: path

Is there anything I am missing out that is causing the test to fail ?

**Comment by filipw** [comment]
The test only waits for 2 seconds for a new file, if it takes longer to notify the workspace it will fail. This can happen on network shares or when write permissions are missing. Since this is an older issue and it has been stable on CI builds too I will close this, let's revisit if it happens again.
