### ISSUE TITLE
Intellisense stopped working, errors in VS Code Console

### ISSUE THREAD

**Issue by thnk2wn** [OmniSharp/omnisharp-roslyn#1339]
Using the latest 1.17.1 version of the extension with VS Code 1.29.1. Made some code changes to a C# file in a .net core 2.1 console app and intellisense stopped working, can't seem to get it to work again. The code compiles fine.

There are no errors or warnings in the OmniSharp Log Output but toggling VS Code Developer tools I do see some errors:

<pre>
ERR Cannot read property 'selection' of undefined: TypeError: Cannot read property 'selection' of undefined
    at CodeActionProvider.getInitializeFromCtorCommand (C:\Users\geoffh\.vscode\extensions\jchannon.csharpextensions-1.3.0\out\src\codeActionProvider.js:165:33)
    at addInitalizeFromCtor (C:\Users\geoffh\.vscode\extensions\jchannon.csharpextensions-1.3.0\out\src\codeActionProvider.js:15:28)
    at CodeActionProvider.provideCodeActions (C:\Users\geoffh\.vscode\extensions\jchannon.csharpextensions-1.3.0\out\src\codeActionProvider.js:19:9)
    at c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:509:787
    at c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:114:65
    at new Promise (<anonymous>:null:null)
    at Object.t.asThenable (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:114:33)
    at e.provideCodeActions (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:509:746)
    at c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:524:308
    at e._withAdapter (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:520:234)
    at e.$provideCodeActions (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:524:270)
    at t._doInvokeHandler (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:757)
    at t._invokeHandler (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:423)
    at t._receiveRequest (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:607:973)
    at t._receiveOneMessage (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:606:957)
    at c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
    at c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
    at e.fire (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
    at a (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
    at Socket._socketDataListener (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
</pre>

<pre>
ERR Pending request cancelled: /typelookup: Error: Pending request cancelled: /typelookup
    at RequestQueue.cancelRequest (C:\Users\geoffh\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:45:29)
    at RequestQueueCollection.cancelRequest (C:\Users\geoffh\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:115:15)
    at token.onCancellationRequested (C:\Users\geoffh\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:413:40)
    at e.fire (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
    at e.cancel (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:72)
    at e.cancel (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:794)
    at Object.c (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:607:1017)
    at t._receiveCancel (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:753)
    at t._receiveOneMessage (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:607:276)
    at c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
    at c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
    at e.fire (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
    at a (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
    at Socket._socketDataListener (c:\Users\geoffh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
</pre>

<pre>
/C:/Users/geoffh/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] rejected promise not handled within 1 second
t.log @ /C:/Users/geoffh/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294
/C:/Users/geoffh/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1446   ERR An unknown error occurred. Please consult the log for more details.
</pre>

**Comment by DustinCampbell** [comment]
cc @rchande. This looks likes an issue for omnisharp-vscode.

**Comment by rchande** [comment]
Moved to https://github.com/OmniSharp/omnisharp-vscode/issues/2715
