### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by hifall** [OmniSharp/omnisharp-roslyn#1366]
I am using Monaco editor to connect to Omnisharp-Roslyn server, with these args:
`--verbose,--stdio,--languageserver`. I am on Omnisharp-Roslyn v1.32.8, and Ubuntu 16.04.

Server initialization seems fine, but when I try to evoke completion on the snippet below:
<img width="519" alt="screen shot 2018-12-16 at 9 02 36 am" src="https://user-images.githubusercontent.com/5734293/50048877-732e5980-0111-11e9-97bc-486f9f0f7479.png">
I get the following message from the browser console:

C# Language Client: [Error - 8:53:37 AM] [crit]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Failed to handle notification textDocument/completion
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at Microsoft.CodeAnalysis.Text.StringText.get_Item (System.Int32 position) [0x00000] in <45499d95dd89417f88ab4e01794e214c>:0 
  at Microsoft.CodeAnalysis.Completion.CommonCompletionUtilities.GetWordSpan (Microsoft.CodeAnalysis.Text.SourceText text, System.Int32 position, System.Func`2[T,TResult] isWordStartCharacter, System.Func`2[T,TResult] isWordCharacter) [0x0000c] in <67e230d5bb4c4250b7d325af5e3bb368>:0 
  at Microsoft.CodeAnalysis.CSharp.Completion.Providers.CompletionUtilities.GetCompletionItemSpan (Microsoft.CodeAnalysis.Text.SourceText text, System.Int32 position) [0x00000] in <c441fd653e884bf0a658a54676fc26eb>:0 
  at Microsoft.CodeAnalysis.CSharp.Completion.CSharpCompletionService.GetDefaultCompletionListSpan (Microsoft.CodeAnalysis.Text.SourceText text, System.Int32 caretPosition) [0x00000] in <c441fd653e884bf0a658a54676fc26eb>:0 
  at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync (Microsoft.CodeAnalysis.Document document, System.Int32 caretPosition, Microsoft.CodeAnalysis.Completion.CompletionTrigger trigger, System.Collections.Immutable.ImmutableHashSet`1[T] roles, Microsoft.CodeAnalysis.Options.OptionSet options, System.Threading.CancellationToken cancellationToken) [0x000e4] in <67e230d5bb4c4250b7d325af5e3bb368>:0 
  at OmniSharp.Roslyn.CSharp.Services.Intellisense.IntellisenseService.Handle (OmniSharp.Models.AutoComplete.AutoCompleteRequest request) [0x00204] in <38f6f21a8ae345a3962efcf9815e3b60>:0 
  at OmniSharp.LanguageServerProtocol.Handlers.CompletionHandler.Handle (OmniSharp.Extensions.LanguageServer.Models.TextDocumentPositionParams request, System.Threading.CancellationToken token) [0x000f1] in <9de86d2dac2c4138838f3b5439ec582f>:0 
  at OmniSharp.Extensions.LanguageServer.LspRequestRouter.RouteRequest (OmniSharp.Extensions.JsonRpc.IHandlerDescriptor descriptor, OmniSharp.Extensions.JsonRpc.Server.Request request) [0x00161] in <43976da1155b4e5492c57f3d85e24f0e>:0 
console-window.ts:35 C# Language Client: [Error - 8:53:37 AM] Request textDocument/completion failed.
console-window.ts:35 C# Language Client: Error: Internal Error
    at new ResponseError (https://codidate.com/code/main.bundle.js:61529:28)
    at handleResponse (https://codidate.com/code/main.bundle.js:60965:48)
    at processMessageQueue (https://codidate.com/code/main.bundle.js:60793:17)
    at https://codidate.com/code/main.bundle.js:60777:13
    at run (https://codidate.com/code/main.bundle.js:127232:13)
    at runIfPresent (https://codidate.com/code/main.bundle.js:127261:21)
    at onGlobalMessage (https://codidate.com/code/main.bundle.js:127301:17)
console-window.ts:35 C# Language Client: [dbug]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Finding descriptor for textDocument/didChange
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Found attributes 1, ::file:///omnisharp/omnisharp/model/Program.cs
errors.js:60 Uncaught []
(anonymous) @ errors.js:60
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:56
ErrorHandler.onUnexpectedExternalError @ errors.js:75
onUnexpectedExternalError @ errors.js:91
Promise.then (async)
(anonymous) @ suggest.js:47
(anonymous) @ suggest.js:43
loop @ async.js:327
first2 @ async.js:335
provideSuggestionItems @ suggest.js:70
(anonymous) @ suggestModel.js:287
createCancelablePromise @ async.js:33
SuggestModel.trigger @ suggestModel.js:287
(anonymous) @ suggestModel.js:239
(anonymous) @ async.js:387
setTimeout (async)
TimeoutTimer.cancelAndSet @ async.js:385
SuggestModel._onCursorChange @ suggestModel.js:209
(anonymous) @ suggestModel.js:84
Emitter.fire @ event.js:105
(anonymous) @ codeEditorWidget.js:941
Emitter.fire @ event.js:105
Cursor._emitStateChangedIfNecessary @ cursor.js:323
Cursor.trigger @ cursor.js:430
CodeEditorWidget.trigger @ codeEditorWidget.js:620
EditorHandlerCommand.runCommand @ coreCommands.js:1435
handler @ editorExtensions.js:82
InstantiationService.invokeFunction @ instantiationService.js:53
StandaloneCommandService.executeCommand @ simpleServices.js:166
type @ codeEditorWidget.js:999
ViewController.type @ viewController.js:24
(anonymous) @ textAreaHandler.js:194
Emitter.fire @ event.js:105
(anonymous) @ textAreaInput.js:192
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Looking for handler for method textDocument/didChange
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Checking handler textDocument/didChange:OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Registration options OmniSharp.Extensions.LanguageServer.Models.TextDocumentChangeRegistrationOptions
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Document Selector [**/*.cake]
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Checking handler textDocument/didChange:OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Registration options OmniSharp.Extensions.LanguageServer.Models.TextDocumentSaveRegistrationOptions
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Document Selector [**/*.cake]
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Checking handler textDocument/didChange:OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Registration options OmniSharp.Extensions.LanguageServer.Models.TextDocumentChangeRegistrationOptions
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Document Selector [**/*.cs], [**/*.csx]
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Handler Selected: OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler via [**/*.cs], [**/*.csx] (targeting System.RuntimeType)
console-window.ts:35 C# Language Client: [dbug]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Finding descriptor for textDocument/didChange
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Found attributes 1, ::file:///omnisharp/omnisharp/model/Program.cs
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Looking for handler for method textDocument/didChange
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Checking handler textDocument/didChange:OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Registration options OmniSharp.Extensions.LanguageServer.Models.TextDocumentChangeRegistrationOptions
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Document Selector [**/*.cake]
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Checking handler textDocument/didChange:OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Registration options OmniSharp.Extensions.LanguageServer.Models.TextDocumentSaveRegistrationOptions
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Document Selector [**/*.cake]
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Checking handler textDocument/didChange:OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Registration options OmniSharp.Extensions.LanguageServer.Models.TextDocumentChangeRegistrationOptions
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Document Selector [**/*.cs], [**/*.csx]
console-window.ts:35 C# Language Client: [trce]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Handler Selected: OmniSharp.LanguageServerProtocol.Handlers.TextDocumentSyncHandler via [**/*.cs], [**/*.csx] (targeting System.RuntimeType)
console-window.ts:35 C# Language Client: [Error - 8:53:37 AM] [crit]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Failed to handle request textDocument/didChange
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
  at Microsoft.CodeAnalysis.Text.SourceText.CheckSubSpan (Microsoft.CodeAnalysis.Text.TextSpan span) [0x00028] in <45499d95dd89417f88ab4e01794e214c>:0 
  at Microsoft.CodeAnalysis.Text.SourceText.GetSubText (Microsoft.CodeAnalysis.Text.TextSpan span) [0x00000] in <45499d95dd89417f88ab4e01794e214c>:0 
  at Microsoft.CodeAnalysis.Text.SourceText.WithChanges (System.Collections.Generic.IEnumerable`1[T] changes) [0x00144] in <45499d95dd89417f88ab4e01794e214c>:0 
  at Microsoft.CodeAnalysis.Text.SourceText.WithChanges (Microsoft.CodeAnalysis.Text.TextChange[] changes) [0x00000] in <45499d95dd89417f88ab4e01794e214c>:0 
  at OmniSharp.Roslyn.BufferManager.UpdateBufferAsync (OmniSharp.Models.Request request) [0x00317] in <77588daf3b56468d9361c3466db4a07d>:0 
  at OmniSharp.Roslyn.CSharp.Services.Buffer.UpdateBufferService.Handle (OmniSharp.Models.UpdateBuffer.UpdateBufferRequest request) [0x00079] in <38f6f21a8ae345a3962efcf9815e3b60>:0 
  at OmniSharp.Extensions.LanguageServer.LspRequestRouter.RouteNotification (OmniSharp.Extensions.JsonRpc.IHandlerDescriptor handler, OmniSharp.Extensions.JsonRpc.Server.Notification notification) [0x000aa] in <43976da1155b4e5492c57f3d85e24f0e>:0 
console-window.ts:35 C# Language Client: [Error - 8:53:37 AM] [crit]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
        Failed to handle request textDocument/didChange
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
  at Microsoft.CodeAnalysis.Text.SourceText.CheckSubSpan (Microsoft.CodeAnalysis.Text.TextSpan span) [0x00028] in <45499d95dd89417f88ab4e01794e214c>:0 
  at Microsoft.CodeAnalysis.Text.SourceText.GetSubText (Microsoft.CodeAnalysis.Text.TextSpan span) [0x00000] in <45499d95dd89417f88ab4e01794e214c>:0 
  at Microsoft.CodeAnalysis.Text.SourceText.WithChanges (System.Collections.Generic.IEnumerable`1[T] changes) [0x00144] in <45499d95dd89417f88ab4e01794e214c>:0 
  at Microsoft.CodeAnalysis.Text.SourceText.WithChanges (Microsoft.CodeAnalysis.Text.TextChange[] changes) [0x00000] in <45499d95dd89417f88ab4e01794e214c>:0 
  at OmniSharp.Roslyn.BufferManager.UpdateBufferAsync (OmniSharp.Models.Request request) [0x00317] in <77588daf3b56468d9361c3466db4a07d>:0 
  at OmniSharp.Roslyn.CSharp.Services.Buffer.UpdateBufferService.Handle (OmniSharp.Models.UpdateBuffer.UpdateBufferRequest request) [0x00079] in <38f6f21a8ae345a3962efcf9815e3b60>:0 
  at OmniSharp.Extensions.LanguageServer.LspRequestRouter.RouteNotification (OmniSharp.Extensions.JsonRpc.IHandlerDescriptor handler, OmniSharp.Extensions.JsonRpc.Server.Notification notification) [0x000aa] in <43976da1155b4e5492c57f3d85e24f0e>:0 

Apart from that, the server doesn't print any message when this happens.

I'd like to have some help on this, if possible. Thanks!

**Comment by filipw** [comment]
This should be resolved now since LSP completion was reworked.
