### ISSUE TITLE
OmniSharp crashes when loading Roslynator 2.0.2

### ISSUE THREAD

**Issue by feO2x** [OmniSharp/omnisharp-roslyn#1421]
I downloaded [Roslynator 2.0.2](https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2017#overview) and tried to use it with VS Code and OmniSharp according to [the documentation of Roslynator](https://github.com/JosefPihrt/Roslynator/blob/master/docs/RoslynatorForVisualStudioCode.md). Unfortunately, the OmniSharp server crashes during initialization:

```
Starting OmniSharp server at 2019-3-14 10:36:31
    Target: c:\Programming\MsSqlStreaming

OmniSharp server started.
    Path: C:\Users\kenny\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe
    PID: 20528

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2017 15.9.28307.518 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\kenny\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2017 15.9.28307.518 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at OmniSharp.OmniSharpWorkspace..ctor(HostServicesAggregator aggregator, ILoggerFactory loggerFactory, IFileSystemWatcher fileSystemWatcher)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.TypedParts.ActivationFeatures.DisposalFeature.<>c__DisplayClass0_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport[TExport](String contractName)
   at OmniSharp.Stdio.Host.Initialize()
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource)
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.HostHelpers.Start(Func`1 action)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

Here is what I observed so far:

- When I remove `RoslynExtensionsOptions` in omnisharp.json, the OmniSharp server initializes successfully
- When I use Roslynator 2.0.0 instead of 2.0.2, everything works fine

I can't tell exactly if this is an issue with OmniSharp or Roslynator, so maybe @JosefPihrt can take a look, too?

Can I provide you with further log files? The `ReflectionTypeLoadException` doesn't really show which type cannot be loaded properly.

**Comment by JosefPihrt** [comment]
I looked at the [documentation](https://github.com/JosefPihrt/Roslynator/blob/master/docs/RoslynatorForVisualStudioCode.md) and I noticed that library Roslynator.Workspaces.Core.dll is missing from the list of required libraries. This library was added between 2.0.0 and 2.0.2.

Maybe you forgot to copy this library.

**Comment by feO2x** [comment]
@JosefPihrt yes, this works! Thanks for your feedback.
