### ISSUE TITLE
Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll is locked after manual download

### ISSUE THREAD

**Issue by mdarrik** [OmniSharp/omnisharp-roslyn#1687]
I'm getting an error around `Omnisharp.host\CompositionHostBuilder`
Using Windows 10 + VS Code
I've tried with Omnisharp 1.34.9 and 1.34.10-beta.32
(Due to a corporate proxy, have to manually install omnisharp for the VS Code extension, but I don't think it should matter).

```
Registered MSBuild instance: Visual Studio Enterprise 2019 16.4.29613.14 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"

System.NullReferenceException: Object reference not set to an instance of an object.

   at OmniSharp.CompositionHostBuilder.SafeGetTypes(Assembly a) in D:\a\1\s\src\OmniSharp.Host\CompositionHostBuilder.cs:line 106

   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)

   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

   at OmniSharp.CompositionHostBuilder.Build() in D:\a\1\s\src\OmniSharp.Host\CompositionHostBuilder.cs:line 91

   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 47

   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 56

   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 29
```

**Comment by filipw** [comment]
how do you start OmniSharp? 
are you able to provide some repro steps?

**Comment by mdarrik** [comment]
So this is omnisharp started by the VS Code extension. I put this here because I've seen a similar issue moved here. (#1188)

Some output from `dotnet --info`: 
```
Runtime Environment: 
OS Name: Windows
OS Version: 10.0.17763
OS Platform: Windows
RID: win10-x64

```

**Comment by mdarrik** [comment]
So this is omnisharp started by the VS Code extension. I put this here because I've seen a similar issue moved here. (#1188)

Some output from `dotnet --info`: 
```
Runtime Environment: 
OS Name: Windows
OS Version: 10.0.17763
OS Platform: Windows
RID: win10-x64

```

All I've done in terms of repro: 

1. Download the zip files for the version I want (1.34.9 and 1.34.10-beta.32). 
2. Unzip into the {vscode_extensions_folder_path}/ms-vscode.csharp/.omnisharp/{version} folder
3. Create install.Lock
4. Restart vscode or restart omnisharp (using vs code command palette).

It'll throw this error.

**Comment by filipw** [comment]
can you set omnisharp.logginglevel: "debug" and post the full log?

**Comment by mdarrik** [comment]
Here you go: 
```
[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.Cake, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.DotNetTest, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.Host, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.MSBuild, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.Roslyn, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.Roslyn.CSharp, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.Script, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[dbug]: OmniSharp.CompositionHostBuilder

        Loaded OmniSharp.Shared, Version=1.34.0.0, Culture=neutral, PublicKeyToken=null

[fail]: OmniSharp.Services.AssemblyLoader

        Failed to load assembly from path: C:\Users\moby235\.vscode\extensions\ms-vscode.csharp-1.21.9\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll

System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\moby235\.vscode\extensions\ms-vscode.csharp-1.21.9\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

File name: 'file:///C:\Users\moby235\.vscode\extensions\ms-vscode.csharp-1.21.9\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)

   at System.Reflection.Assembly.LoadFrom(String assemblyFile)

   at OmniSharp.Services.AssemblyLoader.LoadFrom(String assemblyPath, Boolean dontLockAssemblyOnDisk) in D:\a\1\s\src\OmniSharp.Host\Services\AssemblyLoader.cs:line 79

 

[info]: OmniSharp.Stdio.Host

        Starting OmniSharp on Windows 6.2.9200.0 (x64)

[info]: OmniSharp.Services.DotNetCliService

        DotNetPath set to dotnet

[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        Located 4 MSBuild instance(s)

            1: Visual Studio Enterprise 2017 15.9.28307.858 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"

            2: Visual Studio Enterprise 2019 16.4.29613.14 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"

            3: Visual Studio Enterprise 2019 16.3.29230.61 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"

            4: StandAlone 16.3 - "C:\Users\moby235\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        SUCCESS: Resolved to 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll' (name-only).

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        SUCCESS: Resolved to 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Tasks.Core.dll' (name-only).

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        SUCCESS: Resolved to 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.dll' (name-only).

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        SUCCESS: Resolved to 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Framework.dll' (name-only).

[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        Registered MSBuild instance: Visual Studio Enterprise 2019 16.4.29613.14 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        Attempting to resolve 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        SUCCESS: Resolved to 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll' (name-only).

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        Attempting to resolve 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator

        SUCCESS: Resolved to 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Framework.dll' (name-only).

System.NullReferenceException: Object reference not set to an instance of an object.

   at OmniSharp.CompositionHostBuilder.SafeGetTypes(Assembly a) in D:\a\1\s\src\OmniSharp.Host\CompositionHostBuilder.cs:line 106

   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)

   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

   at OmniSharp.CompositionHostBuilder.Build() in D:\a\1\s\src\OmniSharp.Host\CompositionHostBuilder.cs:line 91

   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 47

   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 56

   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 29

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

 ```

**Comment by filipw** [comment]
aha, that's great info - thanks.
the reason for the failure is because the Razor plugin cannot be loaded as it gets attempted to be loaded via a network path `file:///C:\Users\moby235\.vscode\extensions\ms-vscode.csharp-1.21.9\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)`

this is quite obscure, weird that this would be happening now as we've always loaded plugins this way.
I wonder if we should enable `<loadFromRemoteSources enabled="true"/>`

is this inside a VM? anything special about this environment? is this really a network location (even though it appears to be the C: drive)

cc @NTaylorMullen who'd be interested in this

**Comment by filipw** [comment]
@mdarrik could you also try to go to the location of the assembly (`C:\Users\moby235\.vscode\extensions\ms-vscode.csharp-1.21.9\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll`) and right-mouse click it. Then go to the General tab and click “unblock” and see if it helps

**Comment by mdarrik** [comment]
Looks like that may have fixed it @filipw. Thanks.

**Comment by mdarrik** [comment]
I can open an issue in the VS-Code extension repo about this, but would it make sense to add documentation on a "manual install" process? It seems like NTLM proxies are going to be a problem for any of the other fixes for the foreseeable future, so helping people work around them could help prevent issues like this.

**Comment by filipw** [comment]
maybe you should open an issue on the Razor plugin repo https://github.com/dotnet/aspnetcore-tooling
looks like somehow nothing was affected, except the one DLL that is the Razor OmniSharp plugin

**Comment by filipw** [comment]
I will close this as this is not an Omnisharp problem.

**Comment by NTaylorMullen** [comment]
> maybe you should open an issue on the Razor plugin repo https://github.com/dotnet/aspnetcore-tooling
> looks like somehow nothing was affected, except the one DLL that is the Razor OmniSharp plugin

So Razor's plugin path is decided here: https://github.com/OmniSharp/omnisharp-vscode/blob/6608b739146123e920f410da5f29b9abfa8309eb/src/omnisharp/server.ts#L322-L326

Razor's plugin loading is handled via O#'s `--plugin` system. Is there something we should be doing differently?
