### ISSUE TITLE
Omnisharp Emacs LSP Error

### ISSUE THREAD

**Issue by passeride** [OmniSharp/omnisharp-roslyn#1689]
Hello

Not sure how to go about debugging this, but this error is frequently seen on the eamcs LSP c-sharp mode on Windows 10 64bit

```
LSP :: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object.

   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpSignatureHelpHandler.<Handle>d__3.MoveNext() in D:\a\1\s\src\OmniSharp.LanguageServerProtocol\Handlers\OmniSharpSignatureHelpHandler.cs:line 45

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.JsonRpc.RequestRouterBase\`1.<RouteRequest>d__6.MoveNext()

```

**Comment by janoc** [comment]
Yep, I am seeing this too:

```
Failed to handle notification textDocument/signatureHelp - System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.

   à OmniSharp.LanguageServerProtocol.Handlers.OmniSharpSignatureHelpHandler.<Handle>d__3.MoveNext() dans D:\a\1\s\src\OmniSharp.LanguageServerProtocol\Handlers\OmniSharpSignatureHelpHandler.cs:ligne 45

--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---

   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   à OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()

--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---

   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   à OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__6.MoveNext()
```

**Comment by kirill-gerasimenko** [comment]
Same for me, but on Linux.

**Comment by david-driscoll** [comment]
Hmm, I know the issue and I'll have to check a few things as to where to make the change.  I'll look at this tonight though for sure.

**Comment by david-driscoll** [comment]
I just took a look, I'll get a fix out to the lsp lib and upgrade here and I'll drop a new release either tonight or tomorrow sometime.

**Comment by janoc** [comment]
Thanks!

**Comment by ericdallo** [comment]
Same issue here, any news on this @david-driscoll?

**Comment by joshbarth** [comment]
Has there been any progress on this? I'm having this issue as well. Everything still works, as far as I can tell, but the error is annoying.

**Comment by razzmatazz** [comment]
Hey @joshbarth 

I might be able to investigate the issue. Do you have a minimal repo with which to reproduce it?
