### ISSUE TITLE
Omnisharp chose the wrong msbuild

### ISSUE THREAD

**Issue by ashuai** [OmniSharp/omnisharp-roslyn#1732]
```
[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.4.29905.134 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\ashuai\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.4.29905.134 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\prj\api\webapp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\prj\api\webapp
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\prj\api\webapp'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\prj\api\webapp\webapp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\prj\api\webapp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\prj\api\webapp\webapp.csproj
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\prj\api\webapp' on host 32172.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\prj\api\webapp\webapp.csproj'.
d:\prj\api\webapp\webapp.csproj(1,1)
System.IO.FileNotFoundException: Unable to load file or assembly
“Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

filename:“Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loadFunc)
```

### Selected directory list
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\Roslyn
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.DiaSymReader.Native.amd64.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.DiaSymReader.Native.x86.dll
```

**How should I choose the correct msbuild manually?**

**Comment by filipw** [comment]
you are using VS Code extension 1.15.2 that is 2 years old, please update to the latest
