### ISSUE TITLE
PathTooLongException

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-roslyn#174]
I'm getting a path too long exception on an ASP.vnext sample project. What puzzles me is that I could work with this project before.

```
[INFORMATION:OmniSharp.AspNet5.AspNet5Paths] Looking for sdk version in 'c:\Users\egamma\Projects\tries\PartsUnlimited\global.json'.
[INFORMATION:OmniSharp.AspNet5.AspNet5Paths] Using runtime 'C:\Users\egamma\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4-11566'.
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] Scanning 'c:\Users\egamma\Projects\tries\PartsUnlimited' for ASP.NET 5 projects
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
   at Microsoft.Framework.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper.<EnumerateFileSystemInfos>d__3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Framework.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Framework.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String directoryPath)
   at OmniSharp.AspNet5.AspNet5ProjectSystem.ScanForProjects()
   at OmniSharp.AspNet5.AspNet5ProjectSystem.Initalize()
   at OmniSharp.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IOmnisharpEnvironment env, ISharedTextWriter writer)
```

**Comment by jrieken** [comment]
@davidfowl - this seems to be the ```Microsoft.Framework.FileSystemGlobbing``` library recently added. Is that known to be troublesome with long paths? Iff so we could go with the coreclr code path.

**Comment by davidfowl** [comment]
Will look into it. I assume this is the usual node modules issue.

**Comment by egamma** [comment]
Yes that could explain why it worked on first open. On first open the node modules are not restored and on second restore the node modules are there and then the file system globber dives into the node modules.  An ugly work around is to exclude the node modules folder from the matching. There are no projects in the node modules folder.

**Comment by davidfowl** [comment]
I think that's the cheapest hack we can do for now. @jrieken filed an issue to look at how we generally scan for projects on open.

**Comment by luisrudge** [comment]
I'm having this issue too.

**Comment by nosami** [comment]
Closing as an editor integration issue.
