### ISSUE TITLE
Omnisharp Server crashing with a NullReferenceException 

### ISSUE THREAD

**Issue by BeminAbe** [OmniSharp/omnisharp-roslyn#2125]
## Issue Description ##
Omnisharp keeps throwing a NullReferenceException only when opening a c# file in our Client Project.
Our workspace is a blazorwasm application split into multiple Projects Client, Server, Shared and Core.

## Steps to Reproduce ##
As of right now I haven't found any.

## Expected Behavior ##
O# Server not crashing.

## Actual Behavior ##
O# Server crashing due to NullReferenceException.

### OmniSharp log ###
<details>

```

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniSharp.Helpers.LocationExtensions.<>c__DisplayClass0_0.<GetQuickFix>b__3(Document d) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 45
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OmniSharp.Helpers.LocationExtensions.<GetQuickFix>g__GetSourceText|0_0(Location location, IEnumerable`1 documents, Boolean hasMappedPath) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 45
   at OmniSharp.Helpers.LocationExtensions.GetQuickFix(Location location, OmniSharpWorkspace workspace) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 19
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at OmniSharp.Protocol.Packet.ToString() in D:\a\1\s\src\OmniSharp.Host\Protocol\Packet.cs:line 22
   at System.IO.TextWriter.WriteLine(Object value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at OmniSharp.Services.SharedTextWriter.ProcessWriteQueue() in D:\a\1\s\src\OmniSharp.Host\Services\SharedTextWriter.cs:line 48
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
</details>

## Environment information ##

**VSCode version**: 1.55.0
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.9|;
</details>

**Comment by JoeRobich** [comment]
@filipw Looks like this change might have caused a NRE https://github.com/OmniSharp/omnisharp-roslyn/commit/e502657ce008157d5a69bc19bf48d20a310c2f87

**Comment by filipw** [comment]
It crashes on that line, but I'd say that crash can only happen if we have a `null` document, which should never happen.
So to me it seems like the null reference is a symptom, but not the root cause for the actual problem.

It would be good to have the repro project.

**Comment by filipw** [comment]
@BeminAbe are you able to provide a repro project for this?

**Comment by BeminAbe** [comment]
As of right now I don't have a repro project. Are there any tools/settings I can use that may help me with making one?

**Comment by NTaylorMullen** [comment]
Just ran into this by building/running local O#-vscode as well:
![image](https://user-images.githubusercontent.com/2008729/114469648-6e272b00-9ba2-11eb-84c9-a1ba1d12a5c2.png)

**Comment by NTaylorMullen** [comment]
Was running in a Blazor web project if it helps

**Comment by BeminAbe** [comment]
@NTaylorMullen Which version of dotnet were you running?
I had the issue when my team was running 6.0.100-preview.2.21155.3 but due to the shear amount of problems we encountered we had to switch back to Version 5.0.202 which doesn't seem to have this issue.

**Comment by NTaylorMullen** [comment]
6.0.0-preview.2.21118.6

**Comment by Duckers** [comment]
Same problem in a vanilla ASP.NET Core MVC template, repro attached:
[McvTest.zip](https://github.com/OmniSharp/omnisharp-roslyn/files/6721724/McvTest.zip)

Open any C# file, and OmniSharp crashes with the same stack trace as others have got above

**Comment by TheAifam5** [comment]
Me too. Tried that NRE patch but still crashes with the same stacktrace.

**Comment by JosNun** [comment]
Not a 100% solution, but a temp workaround for me to at least temporarily prevent the crashing was to replace [this line](https://github.com/OmniSharp/omnisharp-roslyn/blob/a9da26fba4ab2142a1a7fd00668405257ab54cbc/src/OmniSharp.Roslyn.CSharp/Helpers/LocationExtensions.cs#L35) with 
```Projects = documents.Where(document => document?.Project?.Name != null).Select(document => document?.Project?.Name).ToArray(),```

It's not a 100% solution, since it doesn't address the root of the issue, and an error is still logged in the console (though, it's gracefully handled), but the patch at least prevented it from crashing all the time and being generally unusable with the latest preview versions of .NET 6.

**Comment by Xeevis** [comment]
Another tempfix that will stop Omnisharp from crashing just after opening `.cs` files is to disable References Code Lens. `"csharp.referencesCodeLens.enabled": false`. This will not prevent crash when you try to seek the references manually however.

This issue is happening for `.cs` files that have types that are used inside `.razor` files. So when CodeLens tries to retrieve references, it will attempt to load documents for `.razor` files that are for some reason not present in the `CurrentSolution`. 

When it's calling this line
https://github.com/OmniSharp/omnisharp-roslyn/blob/9c293cbce30d17875526220a718a8396d987d626/src/OmniSharp.Roslyn.CSharp/Helpers/LocationExtensions.cs#L23

where `lineSpan.Path` is for example `e:/BlazorApp/src/Client/Shared/MainLayout.razor`

This code will respond with `null` which eventually leads to NRE.

https://github.com/OmniSharp/omnisharp-roslyn/blob/9c293cbce30d17875526220a718a8396d987d626/src/OmniSharp.Roslyn/OmniSharpWorkspace.cs#L339-L344

`.cs <-> .cs` references work fine. Only `.cs -> .razor` is broken.

**Comment by Igorgro** [comment]
Having exactly th same issue. It happens at random moments for example when adding modifiers to class members or when moving or copy code lines.
```
Unhandled Exception: System.NullReferenceException:  Object reference not set to an instance of an object.
   at OmniSharp.Helpers.LocationExtensions.<>c.<GetQuickFix>b__0_2(Document document) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 40
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OmniSharp.Helpers.LocationExtensions.GetQuickFix(Location location, OmniSharpWorkspace workspace) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 32
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at OmniSharp.Protocol.Packet.ToString() in D:\a\1\s\src\OmniSharp.Host\Protocol\Packet.cs:line 22
   at System.IO.TextWriter.WriteLine(Object value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at OmniSharp.Services.SharedTextWriter.ProcessWriteQueue() in D:\a\1\s\src\OmniSharp.Host\Services\SharedTextWriter.cs:line 48
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mikechari** [comment]
Maybe related suddenly i am getting this one:
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniSharp.Helpers.DiagnosticExtensions.<>c.<DistinctDiagnosticLocationsByProject>b__2_0(DocumentDiagnostics x) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\DiagnosticExtensions.cs:line 38
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at OmniSharp.Protocol.Packet.ToString() in D:\a\1\s\src\OmniSharp.Host\Protocol\Packet.cs:line 22
   at System.IO.TextWriter.WriteLine(Object value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at OmniSharp.Services.SharedTextWriter.ProcessWriteQueue() in D:\a\1\s\src\OmniSharp.Host\Services\SharedTextWriter.cs:line 48
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by filipw** [comment]
@mikechari not related. remove "omnisharp.path":"latest" from your settings, as that opts you into the latest prerelease of OmniSharp which contains a regression
