### ISSUE TITLE
Solution based project returns `System.ArgumentException: An item with the same key has already been added.`

### ISSUE THREAD

**Issue by microhobby** [OmniSharp/omnisharp-roslyn#2133]
Trying to load a shared project with a solution file returns the follows:

```
Starting OmniSharp server at 4/9/2021, 5:45:13 PM
    Target: c:\Users\mpro3\source\Documentation\Documentation.sln

OmniSharp server started.
    Path: c:\Users\mpro3\.vscode-insiders\extensions\ms-dotnettools.csharp-1.23.10\.omnisharp\1.37.8\OmniSharp.exe
    PID: 17232

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.9.28307.1401 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: Visual Studio Community 2019 16.10.31025.218 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            3: StandAlone 16.9.0 - "c:\Users\mpro3\.vscode-insiders\extensions\ms-dotnettools.csharp-1.23.10\.omnisharp\1.37.8\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.10.31025.218 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\mpro3\source\Documentation'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\mpro3\source\Documentation\Documentation.sln'.
[fail]: OmniSharp.WorkspaceInitializer
        The project system 'OmniSharp.MSBuild.ProjectSystem' threw exception during initialization.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OmniSharp.MSBuild.ProjectSystem.GetProjectPathsAndIdsFromSolutionOrFilter(String solutionOrFilterFilePath, String& solutionFilePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectSystem.cs:line 195
   at OmniSharp.MSBuild.ProjectSystem.Initalize(IConfiguration configuration) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectSystem.cs:line 117
   at OmniSharp.WorkspaceInitializer.Initialize(IServiceProvider serviceProvider, CompositionHost compositionHost) in D:\a\1\s\src\OmniSharp.Host\WorkspaceInitializer.cs:line 54
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\mpro3\source\Documentation'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\mpro3\source\Documentation' on host 11004.
Received response for /v2/getcodeactions but could not find request.

```

This cause the VS Code extension to not work, to not load the solution.

**Comment by microhobby** [comment]
Project that I'm using for reproduce:


[Documentation.zip](https://github.com/OmniSharp/omnisharp-roslyn/files/6288480/Documentation.zip)

**Comment by JoeRobich** [comment]
@microhobby You have duplicate configuration entries for the project with id "{fd085188-cf5a-4c6e-bb1e-9b9338862b69}" in the Documentation.sln file. Lines 158-196 are duplicated as lines 198-225. If I remove the 198-225 block of config, the solution will load.

**Comment by microhobby** [comment]
@JoeRobich thanks for the tip. Yes it loads now, removing the lines, but intelliSense doesn't work anymore:

![image](https://user-images.githubusercontent.com/2633321/114244359-b0fbbf80-9964-11eb-992f-02f9dbe7c1db.png)

I think those lines have something to do with it, I don't know much about sln files using shared projects, but this file opens ok in VS 2019 and it opened ok in version 1.37.0

**Comment by microhobby** [comment]
@JoeRobich oh wait, I reload it, clicking in the `Documentation.sln` and selecting again and now it worked. Sorry for the silly comment above. 

![image](https://user-images.githubusercontent.com/2633321/114244964-e0f79280-9965-11eb-9266-ee9d1d5ef917.png)

I will open an issue on the Uno Platform repo, that creates the Solution, thank you 👍🏽

**Comment by JoeRobich** [comment]
@microhobby Glad it is working for you! Closing this issue.

**Comment by explorest** [comment]
Oh wow --- I had the same exact issue ( also linked in a comment above). This fix worked perfectly for me as well. 
Thanks @microhobby for taking it up ---  and  @JoeRobich for solving it.
