### ISSUE TITLE
CSX crashes OmniSharp when dependent file not found

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#214]
Have code like below but don't have the referenced file. OmniSharp crashed hard.

```
#load "model.csx"
Console.WriteLine("Hello World");
var i = 99;
Console.WriteLine(i * 8);
```

error:

```
System.IO.FileNotFoundException: Could not find file 'c:\Users\jrieken\AppData\Local\Temp\_monacodata_9888\workspaces\ConsoleApp%20-%20Copy\model.csx'.
File name: 'c:\Users\jrieken\AppData\Local\Temp\_monacodata_9888\workspaces\ConsoleApp%20-%20Copy\model.csx'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at ScriptCs.FileSystem.ReadFileLines(String path)
   at ScriptCs.FilePreProcessor.ParseFile(String path, FileParserContext context)
   at ScriptCs.LoadLineProcessor.ProcessLine(IFileParser parser, FileParserContext context, String line)
   at ScriptCs.Contracts.DirectiveLineProcessor.ProcessLine(IFileParser parser, FileParserContext context, String line, Boolean isBeforeCode)
   at ScriptCs.FilePreProcessor.<>c__DisplayClassd.<ParseScript>b__a(ILineProcessor x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at ScriptCs.FilePreProcessor.ParseScript(List`1 scriptLines, FileParserContext context)
   at ScriptCs.FilePreProcessor.<>c__DisplayClass8.<ParseFile>b__7()
   at ScriptCs.FilePreProcessor.InDirectory(String path, Action action)
   at ScriptCs.FilePreProcessor.ParseFile(String path, FileParserContext context)
   at ScriptCs.FilePreProcessor.<>c__DisplayClass1.<ProcessFile>b__0(FileParserContext context)
....
```

**Comment by nosami** [comment]
@filipw promised to fix any scriptcs bugs :)

**Comment by filipw** [comment]
yeah the whole thing should be wrapped into a big `try catch`; it should just be no op in case of any error or issue

**Comment by filipw** [comment]
the same applies to not finding a DLL referenced with `#r "Something"`

for example: `#r "System.ServiceModel.Security"` (it will default to GAC lookup) - will work on Windows, but since it's not available on Mono, it will crash there

**Comment by jrieken** [comment]
great.

**Comment by nosami** [comment]
Does scriptcs have good error messages for cases like these?

**Comment by filipw** [comment]
yeah but they are handled in the `.exe` not in the core packages used here. Either way, we should strengthen this so that stuff never remains unhandled

**Comment by jrieken** [comment]
this has been fixed
