### ISSUE TITLE
coredumps on ubuntu 20.04

### ISSUE THREAD

**Issue by unhammer** [OmniSharp/omnisharp-roslyn#2162]
I'm getting a core dump on Ubuntu 20.04. I've installed mono-complete from mono-project's repo, and https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.37.10/omnisharp-linux-x64.tar.gz using lsp-mode:

```
$ cat /etc/apt/sources.list.d/mono-official-stable.list
deb https://download.mono-project.com/repo/ubuntu stable-focal main

$ mono --version
Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:33:28 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

$ mono ~/.emacs.d/.cache/lsp/omnisharp-roslyn/v1.37.10/omnisharp/OmniSharp.exe
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Stdio.Host","Message":"Starting OmniSharp on ubuntu 20.4 (x64)"},"Seq":1,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Services.DotNetCliService","Message":"DotNetPath set to dotnet"},"Seq":2,"Type":"event"}
free(): invalid pointer

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x5645b4df4c4b - mono :
	0x5645b4df4fdd - mono :
	0x5645b4da1e47 - mono :
	0x5645b4df41cc - mono :
	0x7f85389613c0 - /lib/x86_64-linux-gnu/libpthread.so.0 :
	0x7f853845318b - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
	0x7f8538432859 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x7f853849d3ee - /lib/x86_64-linux-gnu/libc.so.6 :
	0x7f85384a547c - /lib/x86_64-linux-gnu/libc.so.6 :
	0x7f85384a6cac - /lib/x86_64-linux-gnu/libc.so.6 :
	0x406fbf83 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x140210080835328x from 0x140210151131136x
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Pkilling 0x140210095490816x from 0x140210151131136x
Pkilling 0x140210091288320x from 0x140210151131136x
Pkilling 0x140210082936576x from 0x140210151131136x
Pkilling 0x140210141558528x from 0x140210151131136x
Pkilling 0x140210065176320x from 0x140210151131136x
Pkilling 0x140210087053056x from 0x140210151131136x
Pkilling 0x140210093389568x from 0x140210151131136x
Pkilling 0x140210089170688x from 0x140210151131136x
Entering thread summarizer pause from 0x140210151131136x
Finished thread summarizer pause from 0x140210151131136x.
Failed to create breadcrumb file (null)/crash_hash_0xc8d96290d

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 615117]
[New LWP 615124]
[New LWP 615230]
[New LWP 615231]
[New LWP 615233]
[New LWP 615237]
[New LWP 615238]
[New LWP 615242]
[New LWP 615248]
[New LWP 615410]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f85384f2dff in __GI___wait4 (pid=615441, stat_loc=0x7fff94a2d814, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
  Id   Target Id                                            Frame
* 1    Thread 0x7f8538408800 (LWP 615109) "mono"            0x00007f85384f2dff in __GI___wait4 (pid=615441, stat_loc=0x7fff94a2d814, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
  2    Thread 0x7f85373ff700 (LWP 615117) "SGen worker"     futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5645b51dd1e8) at ../sysdeps/nptl/futex-internal.h:183
  3    Thread 0x7f8537ae7700 (LWP 615124) "Finalizer"       futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5645b51ce4a0) at ../sysdeps/nptl/futex-internal.h:320
  4    Thread 0x7f8534ef8700 (LWP 615230) "mono"            futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f8534ef7c20, clockid=<optimized out>, expected=0, futex_word=0x5645b51dd888) at ../sysdeps/nptl/futex-internal.h:320
  5    Thread 0x7f8534cf7700 (LWP 615231) "Thread Pool Wor" 0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f8534cf6cd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
  6    Thread 0x7f8534af6700 (LWP 615233) "Thread Pool Wor" 0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f8534af5cd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
  7    Thread 0x7f85348f1700 (LWP 615237) "Thread Pool Wor" 0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f85348f0cd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
  8    Thread 0x7f85346ec700 (LWP 615238) "Thread Pool Wor" 0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f85346ebcd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
  9    Thread 0x7f85342ff700 (LWP 615242) "Timer-Scheduler" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f85342fdf70, clockid=<optimized out>, expected=0, futex_word=0x5645b67e80d8) at ../sysdeps/nptl/futex-internal.h:320
  10   Thread 0x7f85340fe700 (LWP 615248) "ProcessWriteQue" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5645b67e8308) at ../sysdeps/nptl/futex-internal.h:183
  11   Thread 0x7f853320f700 (LWP 615410) "Thread Pool Wor" 0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f853320ecd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320

Thread 11 (Thread 0x7f853320f700 (LWP 615410)):
#0  0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f853320ecd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x5645b51ced88, abstime=abstime@entry=0x7f853320ecd0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f853895f743 in __new_sem_wait_slow (sem=0x5645b51ced88, abstime=0x7f853320ecd0, clockid=0) at sem_waitcommon.c:184
#3  0x00005645b4ff22b8 in ?? ()
#4  0x00005645b4f9fafa in ?? ()
#5  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7f85340fe700 (LWP 615248)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5645b67e8308) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5645b67e82b8, cond=0x5645b67e82e0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5645b67e82e0, mutex=0x5645b67e82b8) at pthread_cond_wait.c:638
#3  0x00005645b504da68 in ?? ()
#4  0x00005645b4faac7a in ?? ()
#5  0x00005645b4fac27a in ?? ()
#6  0x00005645b4fe62de in ?? ()
#7  0x00005645b4f2f62b in ?? ()
#8  0x0000000040609baa in ?? ()
#9  0x00007f85374285e8 in ?? ()
#10 0xffffffffffffffff in ?? ()
#11 0x00007f8537428518 in ?? ()
#12 0xffffffffffffffff in ?? ()
#13 0x00007f8537428518 in ?? ()
#14 0x00005645b6c32fa0 in ?? ()
#15 0x00007f85340fd570 in ?? ()
#16 0x00007f85340fd4e0 in ?? ()
#17 0x00007f8537428518 in ?? ()
#18 0x0000000040609954 in ?? ()
#19 0x00007f85374283b8 in ?? ()
#20 0x0000000000000000 in ?? ()

Thread 9 (Thread 0x7f85342ff700 (LWP 615242)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f85342fdf70, clockid=<optimized out>, expected=0, futex_word=0x5645b67e80d8) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7f85342fdf70, clockid=<optimized out>, mutex=0x5645b67e8088, cond=0x5645b67e80b0) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x5645b67e80b0, mutex=0x5645b67e8088, abstime=0x7f85342fdf70) at pthread_cond_wait.c:656
#3  0x00005645b504da0e in ?? ()
#4  0x00005645b4faac7a in ?? ()
#5  0x00005645b4fac2eb in ?? ()
#6  0x00005645b4facb10 in ?? ()
#7  0x00005645b4f9cf9a in ?? ()
#8  0x00005645b4f319a6 in ?? ()
#9  0x00000000406048c2 in ?? ()
#10 0x00007f853741b388 in ?? ()
#11 0x00007f853741b2e8 in ?? ()
#12 0x0000000000000000 in ?? ()

Thread 8 (Thread 0x7f85346ec700 (LWP 615238)):
#0  0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f85346ebcd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x5645b51ced88, abstime=abstime@entry=0x7f85346ebcd0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f853895f743 in __new_sem_wait_slow (sem=0x5645b51ced88, abstime=0x7f85346ebcd0, clockid=0) at sem_waitcommon.c:184
#3  0x00005645b4ff22b8 in ?? ()
#4  0x00005645b4f9fafa in ?? ()
#5  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f85348f1700 (LWP 615237)):
#0  0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f85348f0cd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x5645b51ced88, abstime=abstime@entry=0x7f85348f0cd0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f853895f743 in __new_sem_wait_slow (sem=0x5645b51ced88, abstime=0x7f85348f0cd0, clockid=0) at sem_waitcommon.c:184
#3  0x00005645b4ff22b8 in ?? ()
#4  0x00005645b4f9fafa in ?? ()
#5  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f8534af6700 (LWP 615233)):
#0  0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f8534af5cd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x5645b51ced88, abstime=abstime@entry=0x7f8534af5cd0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f853895f743 in __new_sem_wait_slow (sem=0x5645b51ced88, abstime=0x7f8534af5cd0, clockid=0) at sem_waitcommon.c:184
#3  0x00005645b4ff22b8 in ?? ()
#4  0x00005645b4f9fafa in ?? ()
#5  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f8534cf7700 (LWP 615231)):
#0  0x00007f853895f618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f8534cf6cd0, clockid=0, expected=0, futex_word=0x5645b51ced88) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x5645b51ced88, abstime=abstime@entry=0x7f8534cf6cd0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f853895f743 in __new_sem_wait_slow (sem=0x5645b51ced88, abstime=0x7f8534cf6cd0, clockid=0) at sem_waitcommon.c:184
#3  0x00005645b4ff22b8 in ?? ()
#4  0x00005645b4f9fafa in ?? ()
#5  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f8534ef8700 (LWP 615230)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f8534ef7c20, clockid=<optimized out>, expected=0, futex_word=0x5645b51dd888) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7f8534ef7c20, clockid=<optimized out>, mutex=0x5645b51dd8a0, cond=0x5645b51dd860) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x5645b51dd860, mutex=0x5645b51dd8a0, abstime=0x7f8534ef7c20) at pthread_cond_wait.c:656
#3  0x00005645b504da0e in ?? ()
#4  0x00005645b50587d9 in ?? ()
#5  0x00005645b4ff2f53 in ?? ()
#6  0x00005645b4f9fafa in ?? ()
#7  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f8537ae7700 (LWP 615124)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5645b51ce4a0) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x5645b51ce4a0, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f853895f4e8 in __new_sem_wait_slow (sem=0x5645b51ce4a0, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00005645b4fe2078 in ?? ()
#4  0x00005645b4f9fafa in ?? ()
#5  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f85373ff700 (LWP 615117)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5645b51dd1e8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5645b51dd200, cond=0x5645b51dd1c0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5645b51dd1c0, mutex=0x5645b51dd200) at pthread_cond_wait.c:638
#3  0x00005645b5040276 in ?? ()
#4  0x00007f8538955609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f853852f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f8538408800 (LWP 615109)):
#0  0x00007f85384f2dff in __GI___wait4 (pid=615441, stat_loc=0x7fff94a2d814, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00005645b4df4ec2 in ?? ()
#2  0x00005645b4df4fdd in ?? ()
#3  0x00005645b4da1e47 in ?? ()
#4  0x00005645b4df41cc in ?? ()
#5  <signal handler called>
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x00007f8538432859 in __GI_abort () at abort.c:79
#8  0x00007f853849d3ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f85385c7285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#9  0x00007f85384a547c in malloc_printerr (str=str@entry=0x7f85385c54ae "free(): invalid pointer") at malloc.c:5347
#10 0x00007f85384a6cac in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#11 0x00000000406fbf83 in ?? ()
#12 0x00007f85374fa3c8 in ?? ()
#13 0x00007f853742c438 in ?? ()
#14 0x00007f85375554f8 in ?? ()
#15 0x0000000000000000 in ?? ()
[Inferior 1 (process 615109) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f853845318b):0x7f853845317b  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7f853845318b  48 8b 84 24 08 01 00 00 64 48 33 04 25 28 00 00  H..$....dH3.%(..
0x7f853845319b  00 75 26 44 89 c0 48 81 c4 18 01 00 00 c3 0f 1f  .u&D..H.........
0x7f85384531ab  80 00 00 00 00 48 8b 15 b9 4c 1a 00 f7 d8 41 b8  .....H...L....A.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at OmniSharp.Utilities.PlatformHelper:Unix_free <0x00092>
	  at OmniSharp.Utilities.PlatformHelper:RealPath <0x0005b>
	  at OmniSharp.Utilities.PlatformHelper:GetMonoRuntimePath <0x001c7>
	  at OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider:GetInstances <0x0007b>
	  at OmniSharp.MSBuild.Discovery.MSBuildLocator:GetInstances <0x000d6>
	  at OmniSharp.MSBuild.Discovery.Extensions:GetBestInstance <0x0008d>
	  at OmniSharp.MSBuild.Discovery.Extensions:RegisterDefaultInstance <0x000a7>
	  at OmniSharp.CompositionHostBuilder:Build <0x001fb>
	  at OmniSharp.Stdio.Host:.ctor <0x001bb>
	  at <>c__DisplayClass0_1:<Main>b__1 <0x00657>
	  at <>c__DisplayClass11_0:<OnExecute>b__0 <0x0003e>
	  at McMaster.Extensions.CommandLineUtils.CommandLineApplication:Execute <0x000be>
	  at OmniSharp.CommandLineApplication:Execute <0x002ff>
	  at <>c__DisplayClass0_0:<Main>b__0 <0x00163>
	  at OmniSharp.HostHelpers:Start <0x0008a>
	  at OmniSharp.Stdio.Driver.Program:Main <0x00107>
	  at <Module>:runtime_invoke_int_object <0x00091>
=================================================================

```

what am I missing?

**Comment by unhammer** [comment]
This was because I had

```
$ echo $LD_PRELOAD
/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
```
apparantly Omnisharp doesn't work with [tcmalloc](https://github.com/google/tcmalloc)
