### ISSUE TITLE
IFileSystem

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-roslyn#217]
Right now lots of code accesses file I/O directly, making it difficult, if not impossible to be unit tested.
Also, old server had an `IFileSystem`.

Should it be introduced to facilitate more testable code?

**Comment by nosami** [comment]
I wanted to do this but @davidfowl was against it (something about things not working for real :) )

You should know that System.IO.Abstractions has some serious problems on mono though.

**Comment by filipw** [comment]
sure on the other hand there all three project systems can explode and crash the server because of failing file I/O. You can fix them manually, but would be nice to have tests after fix too.

@jrieken reported scriptcs issues earlier and below or some scenarios for other project systems:

here is Asp Net 5 project system, executed against a folder that has some folders with locked permissions (it scans all sub folders)
```
λ omnisharp.cmd -s C:\foo.sln
[INFORMATION:OmniSharp.Startup] Omnisharp server running on port '2000' at location 'C:\' on host -1.
[INFORMATION:OmniSharp.AspNet5.AspNet5Paths] Using runtime 'C:\Users\filip\.dnx\runtimes\dnx-clr-win-x86.1.0.0-
beta4'.
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] Scanning 'C:\' for ASP.NET 5 projects
System.UnauthorizedAccessException: Access to the path 'C:\Documents and Settings' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern
, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
   at Microsoft.Framework.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper.<EnumerateFileSystemInfos>d__3.M
oveNext()
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Framework.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Framework.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String dir
ectoryPath)
   at OmniSharp.AspNet5.AspNet5ProjectSystem.ScanForProjects()
   at OmniSharp.AspNet5.AspNet5ProjectSystem.Initalize()
   at OmniSharp.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IOmnisharpEnvironment
env, ISharedTextWriter writer)
```

And MsBuild executed against not existing solution

```
λ omnisharp.cmd -s c:\test\foo.sln
[INFORMATION:OmniSharp.Startup] Omnisharp server running on port '2000' at location 'c:\test' on host -1.
[INFORMATION:OmniSharp.AspNet5.AspNet5Paths] Using runtime 'C:\Users\filip\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4'.
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] Scanning 'c:\test' for ASP.NET 5 projects
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] No project.json based projects found
System.IO.FileNotFoundException: Could not find file 'c:\test\foo.sln'.
File name: 'c:\test\foo.sln'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at OmniSharp.MSBuild.MSBuildProjectSystem.Initalize()
   at OmniSharp.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IOmnisharpEnvironment env, ISharedTextWriter writer)
```

**Comment by jrieken** [comment]
well, we should not use ```IFileSystem``` as an excuse for missing error handling ;-) While I see some benefits from having such an abstraction we can hardly use it in the project system magic: DTH and also MSBuild assume a file system and talk to it straight away.

**Comment by davidfowl** [comment]
@jrieken That.

**Comment by david-driscoll** [comment]
@filipw what are your thoughts today?

**Comment by filipw** [comment]
Let's close this and resurrect if needed, no need to keep open forever
