### ISSUE TITLE
System.NotSupportedException: Cake does not support /v2/highlight

### ISSUE THREAD

**Issue by nils-a** [OmniSharp/omnisharp-roslyn#2328]
When viewing the OmniSharp log in a Cake project, the log shows:

```text
System.NotSupportedException: Cake does not support /v2/highlight
   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\a\1\s\src\OmniSharp.Host\Endpoint\EndpointHandler.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\a\1\s\src\OmniSharp.Host\Endpoint\EndpointHandler.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Stdio.Host.<HandleRequest>d__14.MoveNext() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 218
```

It seems everything is working, though.

**Comment by nils-a** [comment]
Closing this, as I am no longer able to reproduce this error.
