### ISSUE TITLE
[Linux] Server doesn't response

### ISSUE THREAD

**Issue by qmmp123** [OmniSharp/omnisharp-roslyn#2365]
I use omnisharp-vim and get error.
<details>
<summary>Capture log</summary>
2022-03-19 08:05:50,512 ERROR Could not connect to OmniSharp server: http://localhost:34507/checkalivestatus

Traceback (most recent call last):

  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open

    h.request(req.get_method(), req.selector, req.data, headers,

  File "/usr/lib/python3.10/http/client.py", line 1282, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output

    self.send(msg)

  File "/usr/lib/python3.10/http/client.py", line 975, in send

    self.connect()

  File "/usr/lib/python3.10/http/client.py", line 941, in connect

    self.sock = self._create_connection(

  File "/usr/lib/python3.10/socket.py", line 845, in create_connection

    raise err

  File "/usr/lib/python3.10/socket.py", line 833, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

</details>

Software:
OS: ArchLinux
Editor: neovim v0.6.1
Plugin: omnisharp-vim

My settings from init.vim
```
let g:OmniSharp_server_stdio = 0
let g:OmniSharp_server_use_mono = 1
```
Steps to reproduce:
1) Launch neovim
2) Open _file.cs_
3) Install OmniSharp via command :OmniSharpInstall
4) Open Log via :OmniSharpOpenLog

**Comment by nickspoons** [comment]
Is there a reason you're using the python server instead of the stdio server? It's harder to get working and has quite limited functionality. It's basically obsolete.

**Comment by qmmp123** [comment]
@nickspoons Thank you for your reply. I did not think about using stdio server. I've reinstalled OmniSharp with stdio server. That worked for me.Thank you
