### ISSUE TITLE
InlayHints not working on neovim

### ISSUE THREAD

**Issue by codeprefect** [OmniSharp/omnisharp-roslyn#2550]
# Description

The source code indicates that omnisharp-roslyn already supports `InlayHint`, but testing from `neovim` reports that omnisharp does not support `textDocument/inlayHint`

# How to reproduce

Start omnisharp using the following command

```[bash]
omnisharp -z --hostPID {neovimPID} DotNet:enablePackageRestore=false --encoding utf-8 --languageserver \
    FormattingOptions:EnableEditorConfigSupport=true FormattingOptions:OrganizeImports=true \
    MsBuild:LoadProjectsOnDemand=true RoslynExtensionsOptions:EnableAnalyzersSupport=true \
    RoslynExtensionsOptions:EnableImportCompletion=true Sdk:IncludePrereleases=true \
    RoslynExtensionsOptions:InlayHintsOptions:EnableForParameters=true \
    RoslynExtensionsOptions:InlayHintsOptions:ForLiteralParameters=true \
    RoslynExtensionsOptions:InlayHintsOptions:ForIndexerParameters=true \
    RoslynExtensionsOptions:InlayHintsOptions:ForObjectCreationParameters=true \
    RoslynExtensionsOptions:InlayHintsOptions:ForOtherParameters=true \
    RoslynExtensionsOptions:InlayHintsOptions:SuppressForParametersThatDifferOnlyBySuffix=false \
    RoslynExtensionsOptions:InlayHintsOptions:SuppressForParametersThatMatchMethodIntent=false \
    RoslynExtensionsOptions:InlayHintsOptions:SuppressForParametersThatMatchArgumentName=false \
    RoslynExtensionsOptions:InlayHintsOptions:EnableForTypes=true \
    RoslynExtensionsOptions:InlayHintsOptions:ForImplicitVariableTypes=true \
    RoslynExtensionsOptions:InlayHintsOptions:ForLambdaParameterTypes=true \
    RoslynExtensionsOptions:InlayHintsOptions:ForImplicitObjectCreation=true
```

I use a [fork](https://github.com/codeprefect/nvim-lspconfig/commit/0cad504cf1c6e60132fa1be2d8e9fbb960ccdc2a) of `nvim-lspconfig` that adds the necessary command-line parameters to enable `inlayHint`

# LSP Log (original)

```[log]
[WARN][2023-07-12 18:55:36] .../lua/vim/lsp.lua:100	"method textDocument/inlayHint is not supported by any of the servers registered for the current buffer"
[WARN][2023-07-12 18:55:36] .../lua/vim/lsp.lua:100	"method textDocument/inlayHint is not supported by any of the servers registered for the current buffer"
```

# LSP Log (pretending that the server supports inlayHint, so that client can at least send the request)

```[log]
[DEBUG][2023-07-12 18:59:54] .../vim/lsp/rpc.lua:259	"rpc.send"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/inlayHint",  params = {    range = {      ["end"] = {        character = 0,        line = 43      },      start = {        character = 0,        line = 12      }    },    textDocument = {      uri = "file:///Users/*.cs"    }  }}
[DEBUG][2023-07-12 18:59:54] .../lua/vim/lsp.lua:1489	"LSP[omnisharp]"	"client.request"	1	"textDocument/inlayHint"	{  range = {    ["end"] = {      character = 0,      line = 106    },    start = {      character = 0,      line = 0    }  },  textDocument = {    uri = "file:///..*.cs"  }}	<function 1>	14
[DEBUG][2023-07-12 18:59:54] .../vim/lsp/rpc.lua:259	"rpc.send"	{  id = 4,  jsonrpc = "2.0",  method = "textDocument/inlayHint",  params = {    range = {      ["end"] = {        character = 0,        line = 106      },      start = {        character = 0,        line = 0      }    },    textDocument = {      uri = "file:///....*.cs"    }  }}
[DEBUG][2023-07-12 18:59:54] .../vim/lsp/rpc.lua:362	"rpc.receive"	{  error = {    code = -32601,    message = "Method not found - textDocument/inlayHint"  },  id = 3,  jsonrpc = "2.0"}
[DEBUG][2023-07-12 18:59:54] .../vim/lsp/rpc.lua:362	"rpc.receive"	{  error = {    code = -32601,    message = "Method not found - textDocument/inlayHint"  },  id = 4,  jsonrpc = "2.0"}
```

# System Details

```
OS: MacOS Ventura
Neovim: NVIM v0.10.0-dev-4683+g06694203e-Homebrew
Omnisharp: 1.39.7
```

**Comment by madiele** [comment]
I have the same problem with neovim on Windows

**Comment by JorgeHerreraU** [comment]
I second this, neovim is not triggering any inlay hints regardless

**Comment by JoeRobich** [comment]
To support inlay hints we will need a release of https://github.com/OmniSharp/csharp-language-server-protocol with updates from the 3.17 spec.

**Comment by bmvi-kinver** [comment]
I tried the new version of `omnisharp` (1.39.9) in Neovim, but whenever my client tries to get inlay hints I get the following error (or similar): 
```console
omnisharp: -32603: Internal Error - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   at OmniSharp.Extensions.TextExtensions.GetPositionFromLineAndOffset(SourceText text, Int32 lineNumber, Int32 offset) in /home/vsts/work/1/s/src/OmniSharp.Roslyn/Extensions/TextExtensions.cs:line 28
   at OmniSharp.Extensions.TextExtensions.GetSpanFromRange(SourceText text, Range range) in /home/vsts/work/1/s/src/OmniSharp.Roslyn/Extensions/TextExtensions.cs:line 55
   at OmniSharp.Roslyn.CSharp.Services.InlayHints.InlayHintService.Handle(InlayHintRequest request) in /home/vsts/work/1/s/src/OmniSharp.Roslyn.CSharp/Services/InlayHints/InlayHintService.cs:line 60
   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpInlayHintHandler.Handle(InlayHintParams request, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/OmniSharp.LanguageServerProtocol/Handle
rs/OmniSharpInlayHintHandler.cs:line 56
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token,
 ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
``` 
This is my `omnisharp.json` config:
```json
{
  "RoslynExtensionsOptions": {
    "inlayHintsOptions": {
        "enableForParameters": true,
        "forLiteralParameters": true,
        "forIndexerParameters": true,
        "forObjectCreationParameters": true,
        "forOtherParameters": true,
        "suppressForParametersThatDifferOnlyBySuffix": false,
        "suppressForParametersThatMatchMethodIntent": false,
        "suppressForParametersThatMatchArgumentName": false,
        "enableForTypes": true,
        "forImplicitVariableTypes": true,
        "forLambdaParameterTypes": true,
        "forImplicitObjectCreation": true
    }
  }
}
Here is an excerpt from the LSP interaction logs:
`OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request textDocument/inlayHint 4 - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')\n   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)\n   at OmniSharp.Extensions.TextExtensions.GetPositionFromLineAndOffset(SourceText text, Int32 lineNumber, Int32 offset) in /home/vsts/work/1/s/src/OmniSharp.Roslyn/Extensions/TextExtensions.cs:line 28\n   at OmniSharp.Extensions.TextExtensions.GetSpanFromRange(SourceText text, Range range) in /home/vsts/work/1/s/src/OmniSharp.Roslyn/Extensions/TextExtensions.cs:line 55\n   at OmniSharp.Roslyn.CSharp.Services.InlayHints.InlayHintService.Handle(InlayHintRequest request) in /home/vsts/work/1/s/src/OmniSharp.Roslyn.CSharp/Services/InlayHints/InlayHintService.cs:line 60\n   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpInlayHintHandler.Handle(InlayHintParams request, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpInlayHintHandler.cs:line 56\n   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)\n   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)\n   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() | Method='textDocument/inlayHint' RequestId='4'"
` (this is a single line, not sure how to format here)
I lack the knowledge to debug this issue effectively, unfortunately. Any ideas as to what might be wrong? Is the problem my configuration, or is the problem on `omnisharp`'s side?

**Comment by codeprefect** [comment]
I will verify this fix later today. Thanks @JoeRobich

**Comment by tanordheim** [comment]
@bmvi-kinver would you be able to share more about your setup if you have this working? I snooped on your profile but didn't find any dotfiles there :) 

I'm running neovim nightly (`v0.10.0-dev-6823fdb`) with Omnisharp v1.39.10 and my neovim native inlay hints are not working. The LSP server does not seem to report supporting inlay hints (`ciient.server_capabilities.inlayHintProvider == false`) and when I enable it for a buffer manually (`vim.lsp.inlay_hint(0, true)`) I get this:

```
omnisharp: -32603: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                       
   at OmniSharp.LanguageServerProtocol.Helpers.ToTextEdits(LinePositionSpanTextChange[] textChanges)+MoveNext() in /Users/runner/work/1/s/src/OmniSharp.LanguageServerProtocol/Helpers.cs:line 246                                                                                                                                                                             
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)                                                                                                                                                                                                                                                                                             
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)                                                                                                                                                                                                                                                                                            
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.ContainerBase`1..ctor(IEnumerable`1 items)                                                                                                                                                                                                                                                                           
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.Container`1..ctor(IEnumerable`1 items)                                                                                                                                                                                                                                                                               
   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpInlayHintHandler.ToLSPInlayHint(InlayHint hint) in /Users/runner/work/1/s/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpInlayHintHandler.cs:line 77                                                                                                                                                          
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()                                                                                                                                                                                                                                                                                                                    
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.ContainerBase`1..ctor(IEnumerable`1 items)                                                                                                                                                                                                                                                                           
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.InlayHintContainer..ctor(IEnumerable`1 items)                                                                                                                                                                                                                                                                        
   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpInlayHintHandler.Handle(InlayHintParams request, CancellationToken cancellationToken) in /Users/runner/work/1/s/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpInlayHintHandler.cs:line 58                                                                                                                    
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                          
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                               
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                                                              
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                                                             
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                                                        
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                                                        
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                                                  
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)                                                                                                                                                                                                                  
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)                                                                                                                                              
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)                                                                                                                                                                                                                                
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()                                    
```

**Comment by bmvi-kinver** [comment]
@tanordheim I can certainly share my config, but it seems that I was too quick to pull the trigger as I'm now experiencing the same problem as you are -- but only for particular files, while for other files it appears to be working properly. In my own project, it looks like inlay hints don't work for any files that has `using Pulumi.SomeIdentifier` statements.

**Comment by ppebb** [comment]
Inlay hints work fine for me, although both textDocument_inlayHint AND textDocument_hover are incorrectly reported. As long as I hardcode them as enabled for omnisharp instead of checking client.supportsMethod, it works.

**Comment by shortc** [comment]
I get that same object reference error in both Helix, and VSCode (c# extension installed, OmniSharp enabled, and LSP drivers enabled)

**Comment by madiele** [comment]
In the end I decided to try to build the repo locally and try to find the bug, the problem will happen always when there is a lambda as a parameter of a function (so very common if you use LINQ as an example)

I've successfully made a change to fix the problem! I opened a PR, hopefully it gets merged if I did not miss any detail while debugging the code, in the meanwhile you can build [my branch](https://github.com/madiele/omnisharp-roslyn/tree/lambda-param-nullref) with `build.ps1` and set omnisharp cmd like this somewhere in your config (edit options as needed to you)

```lua
cmd = {
  "C:\\phat\\to\\repo\\omnisharp-roslyn\\artifacts\\publish\\OmniSharp.Stdio.Driver\\win7-x64\\net6.0\\OmniSharp.exe",
  "-z",
  "--hostPID",
  tostring(vim.fn.getpid()),
  "DotNet:enablePackageRestore=false",
  "--encoding",
  "utf-8",
  "--languageserver",
  "FormattingOptions:EnableEditorConfigSupport=true",
  "FormattingOptions:OrganizeImports=true",
  "RoslynExtensionsOptions:EnableAnalyzersSupport=true",
  "RoslynExtensionsOptions:EnableImportCompletion=true",
  "Sdk:IncludePrereleases=true",
},
```

**Comment by mohiden** [comment]
just update your nvim to 0.10 and add omnisharp.json file in your project directory with this 
`{
  "RoslynExtensionsOptions": {
    "inlayHintsOptions": {
        "enableForParameters": true,
        "forLiteralParameters": true,
        "forIndexerParameters": true,
        "forObjectCreationParameters": true,
        "forOtherParameters": true,
        "suppressForParametersThatDifferOnlyBySuffix": false,
        "suppressForParametersThatMatchMethodIntent": false,
        "suppressForParametersThatMatchArgumentName": false,
        "enableForTypes": true,
        "forImplicitVariableTypes": true,
        "forLambdaParameterTypes": true,
        "forImplicitObjectCreation": true
    }
  }
}`

and then in nvim run :lua vim.lsp.inlay_hint.enable(true)

you can set keymap to toggle inlay hint with 
lua vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
