### ISSUE TITLE
Exception thrown when autocomplete is called

### ISSUE THREAD

**Issue by jtbm37** [OmniSharp/omnisharp-roslyn#554]
At this time, I am on the latest on `dev` branch. Latest commit `6d410ed432da8a11988f9ab9668a77599c07fa76`. 

`dotnet --info`
```
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

```
      POST - /autocomplete
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************ Headers ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Length - 8427
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Type - application/x-www-form-urlencoded
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Accept - */*
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Accept-Encoding - deflate, gzip
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Expect - 100-continue
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Host - 192.168.56.101:2000
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      User-Agent - curl/7.38.0
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Body ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      {"WantDocumentationForEveryCompletionResult":false,"WantMethodHeader":true,"WantReturnType":true,"WantSnippet":true,"WantImportableTypes":false,"WordToComplete":"invo","FileName":"c:\\Users\\jtbm37\\Github\\omnisharp-roslyn\\src\\OmniSharp.Roslyn.CSharp\\Services\\Signatures\\SignatureHelpService.cs","Line":"27","Column":"17","Buffer":"[...]"}
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The type initializer for 'OmniSharp.CSharpSyntaxContext' threw an exception.
System.TypeInitializationException: The type initializer for 'OmniSharp.CSharpSyntaxContext' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at OmniSharp.CSharpSyntaxContext..cctor() in C:\Users\jtbm37\Github\omnisharp-roslyn\src\OmniSharp.Roslyn.CSharp\Workers\Intellisense\CSharpSyntaxContext.cs:line 435
   --- End of inner exception stack trace ---
   at OmniSharp.CSharpSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at OmniSharp.Roslyn.CSharp.Services.Intellisense.IntellisenseService.AddKeywords(HashSet`1 completions, SemanticModel model, Int32 position, Boolean wantKind, String wordToComplete) in C:\Users\jtbm37\Github\omnisharp-roslyn\src\OmniSharp.Roslyn.CSharp\Services\Intellisense\IntellisenseService.cs:line 74
   at OmniSharp.Roslyn.CSharp.Services.Intellisense.IntellisenseService.<Handle>d__3.MoveNext() in C:\Users\jtbm37\Github\omnisharp-roslyn\src\OmniSharp.Roslyn.CSharp\Services\Intellisense\IntellisenseService.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext() in C:\Users\jtbm37\Github\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in C:\Users\jtbm37\Github\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext() in C:\Users\jtbm37\Github\omnisharp-roslyn\src\OmniSharp.Host\Middleware\EndpointMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Response ************
info: OmniSharp.Middleware.LoggingMiddleware[0]
      /autocomplete: 500 79ms
```
(For the sake of brevity, I replaced the buffer content with `[...]`)

It is trying to load Microsoft.CodeAnalysis.Workspaces v1.0.0.0 whereas the one on disk is v1.3.0.60429.

**Comment by jtbm37** [comment]
This was when running the produced artifact in `\artifacts\publish\OmniSharp\default\net451\`.

**Comment by jtbm37** [comment]
Note that other functions like `findsymbols` or `gotodefinition` do work fine.

**Comment by jtbm37** [comment]
Found the issue. New packages have been pushed to Nuget. The below BindingRedirects must be added to the config file.

```
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.CodeAnalysis.Workspaces" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.CodeAnalysis.CSharp.Workspaces" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
```

**Comment by jtbm37** [comment]
I am not really sure how you actually include these in the project itself so that they are included every time I publish. Usually you'd have a .config in the root of the project but in .net core I don't know.

**Comment by hal-ler** [comment]
@troydai I assume the following files need to be updated:

https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Roslyn/MetadataHelper.cs
https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Roslyn.CSharp/Workers/Intellisense/CSharpSyntaxContext.cs

**Comment by troydai** [comment]
@david-driscoll is there a reason for us to hardcoded the versions here?

**Comment by willl** [comment]
I suspect the reasons for hardcoded versions were historical (they seem to have been around since at least 2014).

**Comment by hal-ler** [comment]
Would it make sense to use a constant setting in one of the common libraries to all the code loading Microsoft.CodeAnalysis dlls. That would at least allow for a single point of change when updating versions.
