### ISSUE TITLE
build type dependencies causes "The project system 'DotNetProjectSystem' threw exception during initialization." error

### ISSUE THREAD

**Issue by tugberkugurlu** [OmniSharp/omnisharp-roslyn#563]
Not sure how to repro this in isolation but I get this error when I select one of the projects as active one and all intellisense is broken for types on any project level dependencies.

```
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] foobar-http-frontend/.NETFramework,Version=v4.5.1
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 119 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 8 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 27 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] foobar-aspnet-configuration/.NETFramework,Version=v4.5.1
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 30 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 4 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] foobar-aspnet-configuration/.NETStandard,Version=v1.5
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 39 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 4 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] foobar.Domain/.NETFramework,Version=v4.5.1
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 7 and removed 0 file references
[ERROR:OmniSharp.Startup] The project system 'DotNetProjectSystem' threw exception during initialization.
Object reference not set to an instance of an object.
   at OmniSharp.DotNet.DotNetProjectSystem.UpdateProjectReferences(ProjectState state, IEnumerable`1 projectReferencesLatest)
   at OmniSharp.DotNet.DotNetProjectSystem.Update(Boolean allowRestore)
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor)
[INFORMATION:OmniSharp.Startup] Configuration finished.
```

VS Code info:

```
Version 1.0.0
Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
Date 2016-04-13T14:21:33.326Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
```

C# Extension:

![image](https://cloud.githubusercontent.com/assets/328122/15621513/661ba6ae-2459-11e6-8576-17228b755aef.png)

**Comment by tugberkugurlu** [comment]
This seems to be related to build type dependencies. I ditched them and all is fine now which is annoying :s

**Comment by tverboon** [comment]
Is there a reason you are not using the latest version of VSCode and C# plugin?

**Comment by troydai** [comment]
@tugberkugurlu still build type dependencies shouldn't cause this. Can you update the title to reflect that? I think this issue worth tracking.

**Comment by tugberkugurlu** [comment]
@troydai done.

@tverboon I didn't know there was a new version.

**Comment by filipw** [comment]
This should be resolved, in a sense that `DotNetProjectSystem` has been removed 😀
