### ISSUE TITLE
Activating extension `ms-vscode.csharp` failed: Error: Unsupported linux platform.

### ISSUE THREAD

**Issue by bsleys** [OmniSharp/omnisharp-roslyn#617]
I get the above error when executing >Debug: Download .NET Core Debugger.

$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     elementary
 OS Version:  0.4
 OS Platform: Linux
 RID:         elementary.0.4-x64

Console output from Developer Tools Console window: 
threadService.ts:214 [Extension Host] Activating extension `ms-vscode.csharp` failed: Error: Unsupported linux platform.(anonymous function) @ threadService.ts:214emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
threadService.ts:214 [Extension Host] Activating extension `ms-vscode.csharp` failed:  Error: Unsupported linux platform(anonymous function) @ threadService.ts:214emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
threadService.ts:214 [Extension Host] Here is the error stack:  Error: Error: Unsupported linux platform
    at Error (native)
    at getPlatformRuntimeId (/home/bsleys/.vscode/extensions/ms-vscode.csharp-1.3.0/out/coreclr-debug/activate.js:113:27)
    at Object.activate (/home/bsleys/.vscode/extensions/ms-vscode.csharp-1.3.0/out/coreclr-debug/activate.js:35:21)
    at activate (/home/bsleys/.vscode/extensions/ms-vscode.csharp-1.3.0/out/main.js:82:18)
    at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:28405)
    at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:28188)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:28060
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:9648)
    at Object.j.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13226)
    at n.Class.define._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:15054)
    at n.Class.define._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:14495)
    at c (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:18033)
    at G.then.o.(anonymous function) (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:18250)
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:9648)
    at Object.j.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13226)
    at n.Class.define._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:15054)
mainThreadExtensionService.ts:90 Activating extension `ms-vscode.csharp` failed: Error: Unsupported linux platform.

**Comment by willl** [comment]
Looks like an issue for https://github.com/OmniSharp/omnisharp-vscode

**Comment by DustinCampbell** [comment]
This issue will be solved by https://github.com/OmniSharp/omnisharp-vscode/issues/593.

1. Install the latest version of the C# extension within Visual Studio Code.
2. Download and untar the latest OmniSharp for Mono from https://github.com/OmniSharp/omnisharp-roslyn/releases.
3. In Visual Studio Code, select Preferences->User Settings to open settings.json.
4. In settings.json, add a new setting: `"csharp.omnisharp": "/path/to/omnisharp/OmniSharp.exe"` (note: change the path value to point to the location where you untar'd OmniSharp for Mono).
5. In settings.json, add another setting: `"csharp.omnisharpUsesMono": true`.
6. Restart Visual Studio Code.
