### ISSUE TITLE
autocomplete service throwing error

### ISSUE THREAD

**Issue by Sujay-shetty** [OmniSharp/omnisharp-roslyn#680]
Hi,

When autocomplete request(http://localhost:2000/autocomplete) is made it is throwing the below error in Windows7-x64.

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Must be able aggregate the response to spread t
hem out across all plugins for /autocomplete
System.NotSupportedException: Must be able aggregate the response to spread them out acros
s all plugins for /autocomplete
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(
Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(
Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(
Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
info: OmniSharp.Middleware.LoggingMiddleware[0]
      /autocomplete: 500 553ms
```

When server was build, it built without any errors in Windows7-x64.

Also tried downloading the release version(https://github.com/OmniSharp/omnisharp-roslyn/releases) for Windows7-x64, still giving the same error.

**Comment by DustinCampbell** [comment]
What are you passing in your request?

**Comment by Sujay-shetty** [comment]
@DustinCampbell 
Below is the request format.

URL : http://localhost:2000/autocomplete
Body : {"Line":10,"Column":18,"FileName":"E:\runtime-New_configuration\dotnet_test\Program.cs","Buffer":"using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine(\"Hello World!\");
            Console.
        }
    }
}
","WantDocumentationForEveryCompletionResult":"true","WordToComplete":""}

**Comment by powerumc** [comment]
I'm throwing, too

**Comment by sriramks85** [comment]
any solution

**Comment by Sujay-shetty** [comment]
@sriramks85 above error comes due to logger, comment the logger part and try to use it
