### ISSUE TITLE
UriFormatException during the project loading

### ISSUE THREAD

**Issue by Hinidu** [OmniSharp/omnisharp-roslyn#706]
Hello! I'm trying to open a solution for [DynamicData](https://github.com/RolandPheasant/DynamicData) in VS Code 1.7.2 with C# plugin version 1.5.3 but [DynamicData.csproj](https://github.com/RolandPheasant/DynamicData/blob/master/DynamicData/DynamicData.csproj) can't be loaded though other projects in this solution can be loaded without any problems.
The output of the plugin:
```
Starting OmniSharp server at 13.12.2016, 14:28:21
    Target: c:\Code\DynamicData\DynamicData.sln

OmniSharp server started
    Path: C:\Users\pavel.platto\.vscode\extensions\ms-vscode.csharp-1.5.3\bin\omnisharp\OmniSharp.exe
    PID: 11436

OmniSharp: -s c:\Code\DynamicData\DynamicData.sln --hostPID 11524 --stdio DotNet:enablePackageRestore=false --encoding utf-8
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'c:\Code\DynamicData' on host 11524.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in c:\Code\DynamicData
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in 'c:\Code\DynamicData\DynamicData.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from 'c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj
[INFORMATION:OmniSharp#MSBuild] Loading project from 'c:\Code\DynamicData\DynamicData\DynamicData.csproj'.
[WARNING:OmniSharp#MSBuild] Failed to process project file 'c:\Code\DynamicData\DynamicData\DynamicData.csproj'.
c:\Code\DynamicData\DynamicData\DynamicData.csproj(1,1)
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.Build.Shared.FileUtilities.MakeRelative(String basePath, String path)
   at Microsoft.Build.Evaluation.Evaluator`4.ThrowForImportedProjectWithSearchPathsNotFound(ProjectImportPathMatch searchPathMatch, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String projectFilePath, String solutionDirectory, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics) in C:\Projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 102
   at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProjectFileInfo(String projectFilePath) in C:\Projects\omnisharp-roslyn\src\OmniSharp.MSBuild\MSBuildProjectSystem.cs:line 278

[WARNING:OmniSharp#MSBuild] Skipped unsupported project type '.build'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type '.other'
[INFORMATION:OmniSharp#MSBuild] Loading project from 'c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj
[INFORMATION:OmniSharp#MSBuild] Update project: DynamicData.Tests
[WARNING:OmniSharp#MSBuild] Unable to resolve project reference 'c:\Code\DynamicData\DynamicData\DynamicData.csproj' for 'DynamicData.Tests'.
[INFORMATION:OmniSharp#MSBuild] Update project: DynamicData.PLinq
[WARNING:OmniSharp#MSBuild] Unable to resolve project reference 'c:\Code\DynamicData\DynamicData\DynamicData.csproj' for 'DynamicData.PLinq'.
[INFORMATION:OmniSharp.Startup] Configuration finished.
```
Thank you in advance!

**Comment by filipw** [comment]
could be a problem with tools version.
Can you try updating here https://github.com/RolandPheasant/DynamicData/blob/master/DynamicData/DynamicData.csproj#L2 (and all other projects) tools version to `14.0` and see what happens?

**Comment by Hinidu** [comment]
@filipw thanks for the suggestion but nothing is changed. By the way in the log I see that `omnisharp` says that it is `Using tools version: 15.0` for all projects in this solution.

**Comment by filipw** [comment]
can you set `"omnisharp.loggingLevel": "verbose"` in Preferences > User Settings to gather detailed output log?

**Comment by Hinidu** [comment]
Yes, but there are too many output so output window cropped it. Can I find this log somewhere else?

**Comment by Hinidu** [comment]
@filipw I've managed to copy the first bits of the log before they were cropped:
```
Starting OmniSharp server at 14.12.2016, 11:12:52
    Target: c:\Code\DynamicData\DynamicData.sln

OmniSharp server started
    Path: C:\Users\pavel.platto\.vscode\extensions\ms-vscode.csharp-1.5.3\bin\omnisharp\OmniSharp.exe
    PID: 12604

OmniSharp: -s c:\Code\DynamicData\DynamicData.sln --hostPID 10404 --stdio DotNet:enablePackageRestore=false --encoding utf-8 -v
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.DotNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.DotNetTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.Roslyn.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG:OmniSharp.Startup] Loaded OmniSharp.Stdio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'c:\Code\DynamicData' on host 10404.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in c:\Code\DynamicData
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in 'c:\Code\DynamicData\DynamicData.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from 'c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj
[INFORMATION:OmniSharp#MSBuild] Loading project from 'c:\Code\DynamicData\DynamicData\DynamicData.csproj'.
[WARNING:OmniSharp#MSBuild] Failed to process project file 'c:\Code\DynamicData\DynamicData\DynamicData.csproj'.
c:\Code\DynamicData\DynamicData\DynamicData.csproj(1,1)
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.Build.Shared.FileUtilities.MakeRelative(String basePath, String path)
   at Microsoft.Build.Evaluation.Evaluator`4.ThrowForImportedProjectWithSearchPathsNotFound(ProjectImportPathMatch searchPathMatch, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String projectFilePath, String solutionDirectory, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics) in C:\Projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 102
   at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProjectFileInfo(String projectFilePath) in C:\Projects\omnisharp-roslyn\src\OmniSharp.MSBuild\MSBuildProjectSystem.cs:line 278

[WARNING:OmniSharp#MSBuild] Skipped unsupported project type '.build'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type '.other'
[INFORMATION:OmniSharp#MSBuild] Loading project from 'c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj
[INFORMATION:OmniSharp#MSBuild] Update project: DynamicData.Tests
[WARNING:OmniSharp#MSBuild] Unable to resolve project reference 'c:\Code\DynamicData\DynamicData\DynamicData.csproj' for 'DynamicData.Tests'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Microsoft.CSharp.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Microsoft.CSharp.dll' to 'DynamicData.Tests'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll' to 'DynamicData.Tests'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Core.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Core.dll' to 'DynamicData.Tests'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.dll' to 'DynamicData.Tests'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\WindowsBase.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\WindowsBase.dll' to 'DynamicData.Tests'.
[INFORMATION:OmniSharp#MSBuild] Update project: DynamicData.PLinq
[WARNING:OmniSharp#MSBuild] Unable to resolve project reference 'c:\Code\DynamicData\DynamicData\DynamicData.csproj' for 'DynamicData.PLinq'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll' to 'DynamicData.PLinq'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll' to 'DynamicData.PLinq'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll' to 'DynamicData.PLinq'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll' to 'DynamicData.PLinq'.
[DEBUG:OmniSharp.Services.MetadataFileReferenceCache] Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\WindowsBase.dll
[DEBUG:OmniSharp#MSBuild] Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\WindowsBase.dll' to 'DynamicData.PLinq'.
[INFORMATION:OmniSharp.Startup] Configuration finished.
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Request ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Request ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Request ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] POST - /currentfilemembersastree
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] POST - /filesChanged
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] POST - /projects
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Headers ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Headers ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Headers ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] Content-Type - application/json
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] Content-Type - application/json
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Body ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Body ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {
  "Filename": "c:\\Code\\DynamicData\\DynamicData\\Kernel\\DoubleCheck.cs"
}
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] Content-Type - application/json
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Body ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] [
  {
    "Filename": "c:\\Code\\DynamicData\\.git"
  }
]
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Response ************ 
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {}
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Response ************ 
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {"TopLevelTypeDefinitions":[]}
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Request ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] POST - /codecheck
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Headers ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] Content-Type - application/json
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Body ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {
  "Filename": "c:\\Code\\DynamicData\\DynamicData\\Kernel\\DoubleCheck.cs"
}
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Response ************ 
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {"DotNet":{"Projects":[],"RuntimePath":null},"MsBuild":{"SolutionPath":null,"Projects":[]}}
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Response ************ 
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {"QuickFixes":[]}
[DEBUG:OmniSharp.DotNet.DotNetProjectSystem] GetProjectModel: c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj
[DEBUG:OmniSharp#MSBuild] Could not locate project for 'c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj'
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Request ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] POST - /projects
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Headers ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] Content-Type - application/json
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Body ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Response ************ 
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {"DotNet":{"Projects":[],"RuntimePath":null},"MsBuild":{"SolutionPath":null,"Projects":[]}}
[DEBUG:OmniSharp.DotNet.DotNetProjectSystem] GetProjectModel: c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj
[DEBUG:OmniSharp#MSBuild] Could not locate project for 'c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj'
[DEBUG:OmniSharp.DotNet.DotNetProjectSystem] GetProjectModel: c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj
[DEBUG:OmniSharp#MSBuild] Could not locate project for 'c:\Code\DynamicData\DynamicData.Tests\DynamicData.Tests.csproj'
[DEBUG:OmniSharp.DotNet.DotNetProjectSystem] GetProjectModel: c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj
[DEBUG:OmniSharp#MSBuild] Could not locate project for 'c:\Code\DynamicData\DynamicData.PLinq\DynamicData.PLinq.csproj'
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Request ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] POST - /projects
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Headers ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] Content-Type - application/json
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Body ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Response ************ 
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {"DotNet":{"Projects":[],"RuntimePath":null},"MsBuild":{"SolutionPath":null,"Projects":[]}}
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Request ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] POST - /codecheck
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************ Headers ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] Content-Type - application/json
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] ************  Body ************
[DEBUG:OmniSharp.Middleware.LoggingMiddleware] {
  "Filename": null
}
```

**Comment by Hinidu** [comment]
Maybe the problem is that this project is a portable class library while others are plain old .NET libraries?

**Comment by filipw** [comment]
looks like it's the same issue as this https://github.com/OmniSharp/omnisharp-vscode/issues/1045#issue-195817871

**Comment by Hinidu** [comment]
@filipw I think you are right.

**Comment by DustinCampbell** [comment]
@Hinidu: I'm cloning that project now. Will let you know if I see the same issue on v1.6.-beta5 of the VS Code extension.

**Comment by DustinCampbell** [comment]
OK. I didn't see that particular issue. Could you give it a try?

**Comment by filipw** [comment]
I also couldn't reproduce it - all the projects load fine for me

**Comment by Hinidu** [comment]
Thanks! It works now. Though the `UriFormatException` is still in the log.

**Comment by DustinCampbell** [comment]
Note: The issue here is that I included the wrong bits in v1.6-beta5. Unfortunately, it did not include the fix I'd made earlier yesterday. I should have a new one out soonish.

**Comment by Hinidu** [comment]
Ok, I will check the new version too.

**Comment by Hinidu** [comment]
Confirm that exception is gone in v1.6-beta6.

**Comment by DustinCampbell** [comment]
Great! Thanks for verifying
