### ISSUE TITLE
NotSupportedException at /autocomplete

### ISSUE THREAD

**Issue by elondon** [OmniSharp/omnisharp-roslyn#730]
I've been trying to get OmniSharp up and running and I am able to build and run the server - but every time I hit the /autocomplete endpoint, I bomb out. I've tried on both OSX and a clean windows 10 x64 install fresh after checking out the code and building. In both cases, I run into the issue below. Any ideas? I can provide more info if needed, just let me know what you need.

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /autocomplete
System.NotSupportedException: Must be able aggregate the response to spread them out across all plugins for /autocomplete
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext() in C:\code\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.c
s:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in C:\code\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 13
0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext() in C:\code\omnisharp-roslyn\src\OmniSharp.Host\Middleware\EndpointMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
info: OmniSharp.Middleware.LoggingMiddleware[0]
      /autocomplete: 500 269ms

**Comment by willl** [comment]
@elondon What are you passing in your request to the server?

The response `Must be able aggregate the response to spread them out across all plugins` is an indication that you're likely to be passing in incomplete or incorrect to the endpoint `/autocomplete`. 

See the `/autocomplete` [request model](https://github.com/OmniSharp/omnisharp-roslyn/blob/87a9259dbe6de7d61925e213116a696abe301efe/src/OmniSharp.Abstractions/Models/v1/AutoCompleteRequest.cs) to see what it's expecting.

Have a read of the comment by jtbm37, [here](https://github.com/OmniSharp/omnisharp-roslyn/issues/606#issuecomment-231550966).

**Comment by elondon** [comment]
@willl I was just passing WordToComplete. I Tried as a query parameter and as a json body. Are all of the fields in the model required in the request for a valid response?

**Comment by DustinCampbell** [comment]
Here's what we specify in VS Code: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/completionItemProvider.ts#L25-L29

**Comment by elondon** [comment]
Thanks @DustinCampbell - I was actually looking for that block in vscode but must have missed it. With that and some additional info from other posts I was able to get everything working.

It would be nice if there was a bit of official documentation on the API and perhaps some validation so that something more useful than an odd exception popped up in the event of an invalid request. A response indicating missing fields, for example.

Understand everyone is busy - this is a great project. Would love to help out when I have some time.

**Comment by elondon** [comment]
Since @DustinCampbell referenced this in another issue - and for others, here is an example of a request body that works on a fresh build for /autocomplete:

{"Line":10,"Column":18,"FileName":"/Users/elondon/Documents/TestProject/TestProject/Program.cs","WantDocumentationForEveryCompletionResult":"true","WordToComplete":"c"}
