### ISSUE TITLE
"value cannot be null" when attempting to run or debug .net core tests

### ISSUE THREAD

**Issue by KallDrexx** [OmniSharp/omnisharp-roslyn#799]
## Steps to reproduce

1) `mkdir MyApp.Tests`
2) `cd MyApp.Tests`
3) `dotnet new xunit`
4) Open VSCode
5) Define tasks as:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "dotnet",
            "isShellCommand": true,
            "args": [ "build" ],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        },
        {
            "taskName": "test",
            "command": "dotnet",
            "isShellCommand": true,
            "args": [ "test" ],
            "isTestCommand": true
        }
    ]
}
```

6) Build
7) Run test task and verify all tests run successfully
8) Open `UnitTest1.cs` file
9) Click run or debug tasks
---> Observe the following stack trace in the Omnisharp log output:

```
[fail]: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
        An unhandled exception has occurred: Value cannot be null.
Parameter name: path1
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at OmniSharp.DotNetTest.Helpers.ProjectPathResolver.GetProjectPathFromFile(String filepath)
   at OmniSharp.DotNetTest.Services.GetTestStartInfoService.Handle(GetTestStartInfoRequest request)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
[info]: OmniSharp.Middleware.LoggingMiddleware
        /v2/getteststartinfo: 500 11ms
```

VSCode version 1.10.2
Dotnet core tooling: 1.1.1
OS: Windows
C# plugin: 1.8.0

**Comment by DustinCampbell** [comment]
Hi! This particular issue is already tracked in the C# for VS Code repo with https://github.com/OmniSharp/omnisharp-vscode/issues/1100.
