### ISSUE TITLE
unable to build tests on windows 10 x64: missing xunit.runner.utility.desktop.dll

### ISSUE THREAD

**Issue by jmzagorski** [OmniSharp/omnisharp-roslyn#806]
I tried running build.ps1 on windows 10 x64 after getting the net451 developer kit, but it fails `Error: Could not find file ...\omnisharp-roslyn\.tools\xunit.runner.console\tools\xunit.runner.utility.desktop.dll`  (i trimmed the full path in that example) and I can verify the file is not there. I am unsure where to look to try and debug this error or if it is specified to windows 10. I recently migrated from windows 7 where I did not have build errors.

```
omnisharp-roslyn> .\build.ps1
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...

========================================
Cleanup
========================================
Executing task: Cleanup
Finished executing task: Cleanup

========================================
BuildEnvironment
========================================
Executing task: BuildEnvironment
dotnet-install: .NET SDK version 1.0.0-preview2-003121 is already installed.
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
Feeds used:
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

Package "xunit.runner.console.2.2.0" is already installed.
Finished executing task: BuildEnvironment

========================================
PopulateRuntimes
========================================
Executing task: PopulateRuntimes
Finished executing task: PopulateRuntimes

========================================
Setup
========================================
Executing task: Setup
Finished executing task: Setup

========================================
Restore
========================================
Executing task: Restore
Restoring packages....
Package restore successful!
Restoring packages....
Package restore successful!
Finished executing task: Restore

========================================
BuildTest
========================================
Executing task: BuildTest
Finished executing task: BuildTest

========================================
Test
========================================
Executing task: Test
An error occured when executing task 'Test'.
Error: Could not find file ...\omnisharp-roslyn\.tools\xunit.runner.console\tools\xunit.runner.utility.desktop.dll'.
```

**Comment by DustinCampbell** [comment]
Did you pull the latest from the dev branch? This was fixed awhile ago with https://github.com/OmniSharp/omnisharp-roslyn/pull/772.

**Comment by jmzagorski** [comment]
ahh I was pulling this repo from omnisharp-vim and it was not using dev so I manually cloned dev to bypass that error. However, another strange error appeared below `UnauthorizedAccessException`, and I apologize since I have not done research on why this happens yet. I am running the script with admin priveleges...(I substituted %userprofile% in place of my user directory). 

```
========================================
TestCore
========================================
[xUnit.net 00:00:00.9193480]   Discovering: OmniSharp.DotNetTest.Tests
[xUnit.net 00:00:01.1012899]   Discovered:  OmniSharp.DotNetTest.Tests
[xUnit.net 00:00:01.2273020]   Starting:    OmniSharp.DotNetTest.Tests
[xUnit.net 00:00:10.2954715]     OmniSharp.DotNetTest.Tests.LegacyRunTestFacts.RunXunitTest [FAIL]
[xUnit.net 00:00:10.2968061]       System.UnauthorizedAccessException : Access to the path 'LegacyXunitTestProject.dll' is denied.
[xUnit.net 00:00:10.2981373]       Stack Trace:
[xUnit.net 00:00:10.2995010]            at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
[xUnit.net 00:00:10.2997094]            at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
[xUnit.net 00:00:10.2998157]            at System.IO.Directory.Delete(String path, Boolean recursive)
[xUnit.net 00:00:10.2999429]         %userprofile%\.vim\plugin\.cache\.vimrc\.dein\omnisharp-roslyn\tests\TestUtility\TestAssets.TestProject.cs(38,0): at TestUtility.TestAssets.TestProject.Dispose()
[xUnit.net 00:00:10.3004680]         %userprofile%\.vim\plugin\.cache\.vimrc\.dein\omnisharp-roslyn\tests\OmniSharp.DotNetTest.Tests\LegacyRunTestFacts.cs(46,0): at OmniSharp.DotNetTest.Tests.LegacyRunTestFacts.<RunXunitTest>d__3.MoveNext
```

**Comment by DustinCampbell** [comment]
That looks like my fault 😞 I have a fix in a branch I'm working on. Let me try and cherry-pick that to a PR for you.

**Comment by DustinCampbell** [comment]
#807 should address the problem.

**Comment by jmzagorski** [comment]
Thank you for the quick response! As soon as i get back to my computer later tonight I will update this issue

**Comment by jmzagorski** [comment]
that fixed the issue. I think you were right in your pull request comment about it being intermittent. I ran this when I left my computer before grabbing your changes and it worked. Two tries later I got the same error until I grabbed your new dev code. thanks again.

**Comment by DustinCampbell** [comment]
Glad to hear it's working for you now!
