### ISSUE TITLE
v1.16.0 exception when loading Unity3D based sln

### ISSUE THREAD

**Issue by JosephFerano** [OmniSharp/omnisharp-roslyn#839]
Getting the following exception when starting up OmniSharp from Powershell with the following;

`.\OmniSharp.exe -s C:\Users\Joseph\Downloads\Asteroids\Asteroids.sln`

```fail: OmniSharp.Startup[0]
      The project system 'OmniSharp.MSBuild.MSBuildProjectSystem' threw exception during initialization.
Microsoft.Build.Exceptions.InvalidProjectFileException: The solution file has two projects named "Asteroids".  C:\Users\Joseph\Downloads\Asteroids\Asteroids.sln
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.SolutionFile.ParseSolution()
   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()
   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)
   at OmniSharp.MSBuild.MSBuildProjectSystem.GetProjectPathsFromSolution(String solutionFilePath)
   at OmniSharp.MSBuild.MSBuildProjectSystem.GetInitialProjectPaths()
   at OmniSharp.MSBuild.MSBuildProjectSystem.Initalize(IConfiguration configuration)
   at OmniSharp.Startup.InitializeWorkspace(OmniSharpWorkspace workspace, CompositionHost compositionHost, IConfiguration configuration, ILogger logger, OmniSharpOptions options)
```

Trying this on Windows 10. Seems to be a regression as v1.15.0 is working fine.

**Comment by DustinCampbell** [comment]
Thanks for the report. Will take a look.

**Comment by DustinCampbell** [comment]
Thanks for the report. Will take a look. Do you actually have the project defined twice in the solution file?

**Comment by DustinCampbell** [comment]
Any chance you could provide the project.

**Comment by JosephFerano** [comment]
I tested with a newly created Unity3D project. The trick is that you have to add a C# file to a normal directory and to an "Editor" directory, this will generate two csproj files. This is standard behavior in Unity, it will add up to 4 csprojs, here's a typical production Unity3D project in 5.6

```

Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "trolls-main", "Assembly-CSharp.csproj", "{950AC16F-807D-663D-1894-C53D473CC4B0}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "trolls-main", "Assembly-CSharp-Editor-firstpass.csproj", "{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "trolls-main", "Assembly-CSharp-Editor.csproj", "{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{950AC16F-807D-663D-1894-C53D473CC4B0}.Release|Any CPU.Build.0 = Release|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{B2A451EA-51D0-BA77-C03F-0F09DC922A2C}.Release|Any CPU.Build.0 = Release|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{832FEE4E-CEE4-0D41-8C59-5680B8376FE7}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(MonoDevelopProperties) = preSolution
		StartupItem = Assembly-CSharp.csproj
	EndGlobalSection
EndGlobal
```

**Comment by DustinCampbell** [comment]
OK. I can reproduce this. The problem is in MSBuild here: https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Build/Construction/Solution/SolutionFile.cs#L627-L632.

**Comment by DustinCampbell** [comment]
Unity is actually creating a solution that's completely invalid here, but we'll have to live it. MSBuild itself also fails to process a solution file like that. However, VS is resilient against this and can open the file.
