### ISSUE TITLE
FindType And FindSymbols are not working

### ISSUE THREAD

**Issue by exyi** [OmniSharp/omnisharp-roslyn#852]
`/findtypes` and `/findsymbols` are not working, `findtypes` returns no results (probably - vim does not show anything) and `findsymbols` throws an NullReferenceException:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniSharp.Extensions.StringExtensions.IsValidCompletionStartsWithIgnoreCase(String completion, String partial) in /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Roslyn/Extensions/StringExtensions.cs:line 19
   at OmniSharp.Roslyn.CSharp.Services.Navigation.FindSymbolsService.<>c__DisplayClass2_0.<Handle>b__0(String candidate) in /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs:line 29
   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.ContainsName(MergedNamespaceDeclaration mergedRoot, Func`2 predicate, SymbolFilter filter, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ContainsSymbolsWithName(Func`2 predicate, SymbolFilter filter, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.ContainsSymbolsWithNameFromDeclarationOnlyCompilation(Func`2 predicate, SymbolFilter filter, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.<ContainsSymbolsWithNameAsync>d__123.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDeclarationsAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDeclarationsAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDeclarationsAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Roslyn.CSharp.Services.Navigation.FindSymbolsService.<FindSymbols>d__3.MoveNext() in /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Roslyn.CSharp.Services.Navigation.FindSymbolsService.<Handle>d__2.MoveNext() in /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext() in /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Host/Middleware/Endpoint/EndpointHandler.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Host/Middleware/Endpoint/EndpointHandler.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext() in /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/src/OmniSharp.Host/Middleware/EndpointMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
info: OmniSharp.Middleware.LoggingMiddleware[0]
      /findsymbols: 500 4ms
```

I'm running current `dev` version (7bbb03c962ccf04b3756ba95f224d19ec75210a2) on Ubuntu on .NET Core.

**Comment by filipw** [comment]
@exyi do you have a specific repro project?

Can you also post the output from the OmniSharp log?

**Comment by exyi** [comment]
I was trying it on htttps://github.com/riganti/dotvvm.

The startup log: I fails to load some .NET Framework projects, but completion and go-to-definition works on the .NET Core ones, so I'd suppose that find-symbols should work too.

```
OmniSharp: 
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location '/root/code/dotvvm/src' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in /root/code/dotvvm/src
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update project /root/code/dotvvm/src/Samples/AspnetCoreSample
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Add project /root/code/dotvvm/src/Samples/AspnetCoreSample/project.json => af4b641b-24ef-40ba-ac9c-256736ac9de7
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp.DotNet.DotNetProjectSystem[0]
        Processing [ProjectState] AspnetCoreSample/.NETCoreApp,Version=v1.0
info: OmniSharp.Services.DotNetCliService[0]
      Begin dotnet restore in '/root/code/dotvvm/src/Samples/AspnetCoreSample'
info: OmniSharp.DotNet.DotNetProjectSystem[0]
          Added 2 and removed 0 documents.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBUILD_EXE_PATH environment variable set to /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/artifacts/publish/OmniSharp/default/netcoreapp1.1/msbuild/MSBuild.dll
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBuildExtensionsPath environment variable set to /home/developer/.config/nvim/bundle/omnisharp-vim/omnisharp-roslyn/artifacts/publish/OmniSharp/default/netcoreapp1.1/msbuild
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBuild will use local OmniSharp installation.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Detecting projects in '/root/code/dotvvm/src/DotVVM.sln'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework/DotVVM.Framework.csproj
info: OmniSharp.Services.DotNetCliService[0]
      Finish restoring project /root/code/dotvvm/src/Samples/AspnetCoreSample. Exit code 1
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Tests.Javascript/DotVVM.Framework.Tests.Javascript.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Framework.Tests.Javascript/DotVVM.Framework.Tests.Javascript.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Compiler/DotVVM.Compiler.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Compiler/DotVVM.Compiler.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Core/DotVVM.Core.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Samples.BasicSamples.AspNetCore/DotVVM.Samples.BasicSamples.AspNetCore.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Samples.BasicSamples.Owin/DotVVM.Samples.BasicSamples.Owin.csproj
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Samples.BasicSamples.Owin/DotVVM.Samples.BasicSamples.Owin.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Hosting.AspNetCore/DotVVM.Framework.Hosting.AspNetCore.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.CommandLine/DotVVM.CommandLine.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Tests.AspCore/DotVVM.Framework.Tests.AspCore.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Tools.SeleniumGenerator/DotVVM.Framework.Tools.SeleniumGenerator.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Compiler.Light/DotVVM.Compiler.Light.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Tests.Owin/DotVVM.Framework.Tests.Owin.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Framework.Tests.Owin/DotVVM.Framework.Tests.Owin.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Samples.Tests/DotVVM.Samples.Tests.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Samples.Tests/DotVVM.Samples.Tests.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.PerfTests/DotVVM.Framework.PerfTests.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Framework.PerfTests/DotVVM.Framework.PerfTests.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Hosting.Owin/DotVVM.Framework.Hosting.Owin.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Framework.Hosting.Owin/DotVVM.Framework.Hosting.Owin.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Testing.SeleniumHelpers/DotVVM.Framework.Testing.SeleniumHelpers.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/root/code/dotvvm/src/DotVVM.Framework.Testing.SeleniumHelpers/DotVVM.Framework.Testing.SeleniumHelpers.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /root/code/dotvvm/src/DotVVM.Framework.Tests.Common/DotVVM.Framework.Tests.Common.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Framework
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Core
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Samples.Common
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Samples.BasicSamples.AspNetCore
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Framework.Hosting.AspNetCore
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.CommandLine
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Framework.Tests.AspCore
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Framework.Tools.SeleniumGenerator
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Compiler.Light
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: DotVVM.Framework.Tests.Common
info: OmniSharp.Script.ScriptProjectSystem[0]
      Detecting CSX files in '/root/code/dotvvm/src'.
info: OmniSharp.Script.ScriptProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
info: OmniSharp.Startup[0]
      Configuration finished.
```

Also note that I tried to add some random null check to the affected method, and it seems to work:

```diff
diff --git a/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs b/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs index 878938c2..37ce415c 100644
--- a/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs 
+++ b/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs 
@@ -26,7 +26,7 @@ public FindSymbolsService(OmniSharpWorkspace workspace)
         public async Task<QuickFixResponse> Handle(FindSymbolsRequest request = null)
         {
             Func<string, bool> isMatch = 
-                candidate => request != null 
+                candidate => request?.Filter != null
                 ? candidate.IsValidCompletionFor(request.Filter)
                 : true; 
```

**Comment by nickspoons** [comment]
@exyi the roslyn `/findsymbols` endpoint requires a 'Filter' parameter, which OmniSharp-vim doesn't send.

I have just created PR OmniSharp/omnisharp-vim#343 to fix this on the vim end.

Roslyn doesn't have a `/findtypes` endpoint, I don't know if there are plans to add it (and I'm not really sure what it's for?).

**Comment by filipw** [comment]
This should work now since the relevant null checks were added (this can be found in latest releases) and we switched to using `FindSourceDeclarationsWithPatternAsync` (on master, not yet released). Please reopen if you still experience problems. Thanks.
